Repository MultiQC/MultiQC, pull requests merged in 2018-03, with the labels that each got.

#704 New module: DeDup
  CHANGELOG.md
  docs/README.md
  docs/modules/dedup.md
  multiqc/modules/dedup/__init__.py
  multiqc/modules/dedup/dedup.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new

#705 Clip&Merge Module attempt
  CHANGELOG.md
  README.md
  docs/modules/clipandmerge.md
  multiqc/modules/clipandmerge/__init__.py
  multiqc/modules/clipandmerge/clipandmerge.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: awaiting-changes

#714 New feature: path_filters_exclude setting
  CHANGELOG.md
  README.md
  docs/customisation.md
  multiqc/modules/base_module.py
Labels: core: back end
