Repository MultiQC/MultiQC, pull requests merged in 2018-07, with the labels that each got.

#791 Module: fastp
  CHANGELOG.md
  README.md
  docs/README.md
  docs/modules/fastp.md
  multiqc/modules/fastp/__init__.py
  multiqc/modules/fastp/fastp.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new

#727 Set several modules too-global search patterns to share
  multiqc/utils/search_patterns.yaml
Labels: core: back end

#785 New module for HiC-Pro
  CHANGELOG.md
  README.md
  docs/README.md
  docs/modules/hicpro.md
  multiqc/modules/hicpro/__init__.py
  multiqc/modules/hicpro/hicpro.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: awaiting-changes
