Repository MultiQC/MultiQC, pull requests merged in 2020-05, with the labels that each got.

#1176 Fix bug in the samblaster module
  multiqc/modules/samblaster/samblaster.py
Labels: module: change

#1164 Add Rockhopper module
  CHANGELOG.md
  docs/README.md
  docs/modules/rockhopper.md
  multiqc/modules/rockhopper/__init__.py
  multiqc/modules/rockhopper/rockhopper.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new

#1179 Update to sexdeterrmine module. X/Y-rate scatter plot added.
  CHANGELOG.md
  multiqc/modules/sexdeterrmine/sexdeterrmine.py
Labels: awaiting-changes

#1167 Update BISCUIT Module
  CHANGELOG.md
  docs/modules/biscuit.md
  multiqc/modules/biscuit/biscuit.py
  multiqc/utils/search_patterns.yaml
Labels: module: change

#1161 Kraken Module
  CHANGELOG.md
  docs/README.md
  docs/modules.md
  docs/modules/kraken.md
  multiqc/modules/kraken/__init__.py
  multiqc/modules/kraken/kraken.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: WIP, module: new

#1210 Test --ignore-samples
  .github/workflows/multiqc_linux.yml
  .github/workflows/multiqc_windows.yml
  CHANGELOG.md
  docs/modules/goleft_indexcov.md
  multiqc/modules/base_module.py
  multiqc/modules/bbmap/bbmap.py
  multiqc/modules/conpair/conpair.py
  multiqc/modules/deeptools/bamPEFragmentSizeDistribution.py
  multiqc/modules/deeptools/bamPEFragmentSizeTable.py
  multiqc/modules/deeptools/estimateReadFiltering.py
  multiqc/modules/deeptools/plotCorrelation.py
  multiqc/modules/deeptools/plotCoverage.py
  multiqc/modules/deeptools/plotEnrichment.py
  multiqc/modules/deeptools/plotFingerprint.py
  multiqc/modules/deeptools/plotPCA.py
  multiqc/modules/deeptools/plotProfile.py
  multiqc/modules/gatk/base_recalibrator.py
  multiqc/modules/gatk/gatk.py
  multiqc/modules/goleft_indexcov/goleft_indexcov.py
  multiqc/modules/happy/happy.py
  multiqc/modules/hicexplorer/hicexplorer.py
  multiqc/modules/homer/homer.py
  multiqc/modules/homer/tagdirectory.py
  multiqc/modules/interop/interop.py
  multiqc/modules/jellyfish/jellyfish.py
  multiqc/modules/mosdepth/mosdepth.py
  multiqc/modules/pycoqc/pycoqc.py
  multiqc/modules/qualimap/QM_BamQC.py
  multiqc/modules/rna_seqc/rna_seqc.py
  multiqc/modules/seqyclean/seqyclean.py
  multiqc/modules/snpsplit/snpsplit.py
Labels: core: back end
