Repository MultiQC/MultiQC, pull requests merged in 2023-08, with the labels that each got.

#1904 File search optimisations
  multiqc/utils/config_defaults.yaml
  multiqc/utils/report.py
  multiqc/utils/search_patterns.yaml
Labels: priority: high

#1972 Samtools: Stats: fix "Percent Mapped" plot when samtools was run with read filtering
  CHANGELOG.md
  multiqc/modules/samtools/stats.py
Labels: first-approval

#2000 CI: only run full workflow on Linux 3.11. Add helpful messages
  .github/workflows/multiqc.yml
  .github/workflows/multiqc_linux.yml
  .github/workflows/multiqc_windows.yml
  .gitignore
Labels: first-approval

#1981 WhatsHap: ensure that TSV is only split on tab character. Allows sample names with spaces
  CHANGELOG.md
  multiqc/modules/whatshap/whatshap.py
Labels: first-approval

#1968 New submodule for GATK: AnalyzeSaturationMutagenesis
  CHANGELOG.md
  docs/modules/gatk.md
  multiqc/modules/gatk/analyze_saturation_mutagenesis.py
  multiqc/modules/gatk/gatk.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
Labels: first-approval

#1994 DRAGEN: use sample name cleaning patterns instead of hardcoded ones
  CHANGELOG.md
  multiqc/modules/dragen/coverage_hist.py
  multiqc/modules/dragen/coverage_per_contig.py
  multiqc/modules/dragen/dragen_gc_metrics.py
  multiqc/modules/dragen/fragment_length.py
  multiqc/modules/dragen/mapping_metrics.py
  multiqc/modules/dragen/ploidy_estimation_metrics.py
  multiqc/modules/dragen/rna_quant_metrics.py
  multiqc/modules/dragen/rna_transcript_cov.py
  multiqc/modules/dragen/sc_atac_metrics.py
  multiqc/modules/dragen/sc_rna_metrics.py
  multiqc/modules/dragen/time_metrics.py
  multiqc/modules/dragen/trimmer_metrics.py
  multiqc/modules/dragen/vc_metrics.py
  multiqc/utils/config_defaults.yaml
Labels: first-approval

#1993 New module: mapDamage
  CHANGELOG.md
  docs/modules/mapdamage.md
  multiqc/modules/mapdamage/__init__.py
  multiqc/modules/mapdamage/mapdamage.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: first-approval

#1997 NanoStat: support new output format
  CHANGELOG.md
  docs/modules/nanostat.md
  multiqc/modules/nanostat/nanostat.py
  multiqc/utils/search_patterns.yaml
Labels: first-approval

#2005 Mosdepth: fix when there all samples have no coverage
  CHANGELOG.md
  multiqc/modules/mosdepth/mosdepth.py
Labels: awaiting-response-from-user

#1959 new module Bakta
  CHANGELOG.md
  docs/modules/bakta.md
  multiqc/modules/bakta/__init__.py
  multiqc/modules/bakta/bakta.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: first-approval

#2013 fix(core) replace deprecated `pkg_resources`
  CHANGELOG.md
  multiqc/__main__.py
  multiqc/utils/config.py
  multiqc/utils/plugin_hooks.py
  setup.py
Labels: first-approval

#1903 New module: Freyja
  CHANGELOG.md
  docs/modules/freyja.md
  multiqc/modules/freyja/__init__.py
  multiqc/modules/freyja/freyja.py
  multiqc/plots/table.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: first-approval
