Repository MultiQC/MultiQC, pull requests merged in 2023-10, with the labels that each got.

#2094 Picard: MarkDuplicates: account for missing trailing `0`
  CHANGELOG.md
  multiqc/modules/picard/MarkDuplicates.py
Labels: bug: core, first-approval

#2095 Whatshap: process truncated input with no ALL chromosome
  CHANGELOG.md
  multiqc/modules/whatshap/whatshap.py
Labels: first-approval, module: enhancement

#2105 Remove references to the old Gitter chat
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/config.yml
  docs/core/custom_content/index.md
  docs/core/development/modules.md
Labels: documentation

#2102 Trigger changelog entry addition on PR creation, in addition to an explicit comment to multiqc-bot
  .github/workflows/changelog.py
  .github/workflows/changelog.yml
  CHANGELOG.md
  docs/core/development/contributing.md
Labels: first-approval, core: infrastructure

#2101 Strict mode: rename `config.lint` to `config.strict`, crash early on module or template error. Add `MULTIQC_STRICT=1`
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/multiqc.yml
  CHANGELOG.md
  docs/core/custom_content/index.md
  docs/core/development/modules.md
  multiqc/multiqc.py
  multiqc/plots/bargraph.py
  multiqc/plots/linegraph.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/mqc_colour.py
  multiqc/utils/report.py
  multiqc/utils/strict_helpers.py
Labels: first-approval, core: infrastructure

#1751 New module: Truvari
  CHANGELOG.md
  docs/modules/truvari.md
  multiqc/modules/truvari/__init__.py
  multiqc/modules/truvari/bench.py
  multiqc/modules/truvari/truvari.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new, first-approval

#2115 Fix adding changelog entries with backticks from PR titles
  .github/workflows/changelog.yml
  CHANGELOG.md
Labels: first-approval, core: infrastructure

#1626 Exclude zero values, or the y-axis goes up to 100k
  multiqc/modules/picard/HsMetrics.py
Labels: waiting: changes, first-approval

#2117 New logo
  CHANGELOG.md
  README.md
  docs/images/MultiQC_logo.ai
  docs/images/MultiQC_logo.png
  docs/images/MultiQC_logo_darkbg.png
  multiqc/multiqc.py
  multiqc/templates/default/assets/css/default_multiqc.css
  multiqc/templates/default/assets/img/MultiQC_logo.png
  multiqc/templates/default/assets/img/Seqera-Labs.png
  multiqc/templates/default/assets/img/favicon-16x16.png
  multiqc/templates/default/assets/img/favicon-32x32.png
  multiqc/templates/default/assets/img/favicon-96x96.png
  multiqc/templates/default/assets/img/seqera_logo.png
  multiqc/templates/default/assets/img/seqera_logo_mono.png
  multiqc/templates/default/footer.html
  multiqc/templates/default/toolbox.html
Labels: core: front end

#2113 Fix for python 3.12: replace removed `distutils`
  CHANGELOG.md
  multiqc/modules/cutadapt/cutadapt.py
  multiqc/modules/fgbio/ErrorRateByReadPosition.py
  multiqc/modules/picard/CrosscheckFingerprints.py
  multiqc/multiqc.py
  multiqc/utils/util_functions.py
Labels: core: back end

#2119 Bundle lzstring to fix Python 3.12
  CHANGELOG.md
  multiqc/utils/lzstring.py
  multiqc/utils/report.py
  setup.py
Labels: core: back end

#2109 Add `--require-logs` flag to error out if requested modules not used
  CHANGELOG.md
  docs/core/getting_started/running_multiqc.md
  multiqc/multiqc.py
  multiqc/utils/config_defaults.yaml
Labels: core: back end

#2128 Dragen: make sure all inputs are recorded in multiqc_sources.txt
  CHANGELOG.md
  multiqc/modules/dragen/coverage_hist.py
  multiqc/modules/dragen/coverage_metrics.py
  multiqc/modules/dragen/coverage_per_contig.py
  multiqc/modules/dragen/dragen.py
  multiqc/modules/dragen/dragen_gc_metrics.py
  multiqc/modules/dragen/fragment_length.py
  multiqc/modules/dragen/mapping_metrics.py
  multiqc/modules/dragen/overall_mean_cov.py
  multiqc/modules/dragen/ploidy_estimation_metrics.py
  multiqc/modules/dragen/rna_quant_metrics.py
  multiqc/modules/dragen/rna_transcript_cov.py
  multiqc/modules/dragen/sc_atac_metrics.py
  multiqc/modules/dragen/sc_rna_metrics.py
  multiqc/modules/dragen/time_metrics.py
  multiqc/modules/dragen/trimmer_metrics.py
  multiqc/modules/dragen/vc_metrics.py
  multiqc/modules/dragen_fastqc/dragen_fastqc.py
Labels: bug: module

#2127 Picard: adapt WgsMetrics to parabricks bammetrics outputs
  CHANGELOG.md
  multiqc/modules/picard/WgsMetrics.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
Labels: module: change

#2131 Set name and anchor for the custom content "module"
  CHANGELOG.md
  multiqc/modules/base_module.py
  multiqc/modules/custom_content/custom_content.py
Labels: core: back end

#2123 Samtools: Add MQ0 reads to the Percent Mapped barplot in Stats submodule
  CHANGELOG.md
  multiqc/modules/samtools/stats.py
Labels: module: enhancement

#2106 Mosdepth: fix prioritizing region over global information
  CHANGELOG.md
  multiqc/modules/mosdepth/mosdepth.py
Labels: bug: module, first-approval

#2108 Fastp: parse unescaped sample names with white spaces
  CHANGELOG.md
  multiqc/modules/fastp/fastp.py
Labels: first-approval, module: enhancement

#2118 Cellranger: Count submodule updated to parse Antibody Capture summary
  CHANGELOG.md
  docs/modules/cellranger.md
  multiqc/modules/cellranger/count.py
Labels: first-approval

#2142 Changelog bot: detect module updates when only `search_patterns.yaml` changed
  .github/workflows/changelog.py
  .github/workflows/changelog.yml
Labels: core: infrastructure

#2153 Use Ruff formatter instead of Black, pycln, isort
  .github/workflows/changelog.yml
  .pre-commit-config.yaml
  docs/core/development/modules.md
  multiqc/__init__.py
  multiqc/modules/bbmap/plot_aqhist.py
  multiqc/modules/bbmap/plot_bhist.py
  multiqc/modules/bbmap/plot_bqhist.py
  multiqc/modules/bbmap/plot_idhist.py
  multiqc/modules/bbmap/plot_indelhist.py
  multiqc/modules/bbmap/plot_mhist.py
  multiqc/modules/bbmap/plot_qahist.py
  multiqc/modules/bbmap/plot_qhist.py
  multiqc/modules/clusterflow/clusterflow.py
  multiqc/modules/deeptools/plotProfile.py
  multiqc/modules/dragen/coverage_metrics.py
  multiqc/modules/dragen/fragment_length.py
  multiqc/modules/dragen/mapping_metrics.py
  multiqc/modules/multivcfanalyzer/multivcfanalyzer.py
  multiqc/modules/picard/RnaSeqMetrics.py
  multiqc/modules/profile_runtime.py
  multiqc/modules/sentieon/AlignmentSummaryMetrics.py
  multiqc/modules/sentieon/GcBiasMetrics.py
  multiqc/modules/sentieon/InsertSizeMetrics.py
  multiqc/modules/somalier/somalier.py
  multiqc/multiqc.py
  multiqc/plots/bargraph.py
  multiqc/plots/table.py
  pyproject.toml
Labels: needs-review, core: infrastructure
