Repository MultiQC/MultiQC, pull requests merged in 2023-11, with the labels that each got.

#2155 Nanostat: account for both tab and spaces in v1.41+ search pattern
  .github/workflows/changelog.py
  CHANGELOG.md
  multiqc/utils/search_patterns.yaml
Labels: bug: module, needs-review

#2151 New module: Seqera Platform CLI
  .github/workflows/multiqc.yml
  CHANGELOG.md
  CSP.txt
  docs/core/development/modules.md
  docs/core/development/plots.md
  docs/modules/seqera_cli.md
  multiqc/modules/seqera_cli/__init__.py
  multiqc/modules/seqera_cli/seqera_cli.py
  multiqc/modules/truvari/truvari.py
  multiqc/plots/table.py
  multiqc/plots/table_object.py
  multiqc/templates/default/assets/js/multiqc_tables.js
  multiqc/utils/config_defaults.yaml
  multiqc/utils/mqc_colour.py
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new, needs-review

#2159 fastp: add version parsing
  CHANGELOG.md
  multiqc/modules/fastp/fastp.py
Labels: module: enhancement

#2157 Pangolin: update for v4: add QC Note , update tool versions columns
  CHANGELOG.md
  multiqc/modules/pangolin/pangolin.py
Labels: module: enhancement

#2136 Allow unquoted versions in versions YAML
  multiqc/utils/software_versions.py
Labels: core: back end, needs-review

#2143 Fix column order in data exported from matplotlib linegraph with `--data-format tsv --export`
  CHANGELOG.md
  multiqc/modules/dragen_fastqc/base_metrics.py
  multiqc/modules/dragen_fastqc/dragen_fastqc.py
  multiqc/plots/linegraph.py
  multiqc/utils/util_functions.py
Labels: core: back end, needs-review

#2164 Xenome: show percentages by default, add table and sections
  CHANGELOG.md
  docs/modules/xenome.md
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/ngsderive/ngsderive.py
  multiqc/modules/xenome/xenome.py
Labels: module: change, needs-review

#2169 Remove position:absolute from table values
  CHANGELOG.md
  multiqc/templates/default/assets/css/default_multiqc.css
Labels: core: front end

#2170 Fix custom anchors for kraken
  CHANGELOG.md
  multiqc/modules/bracken/bracken.py
  multiqc/modules/kraken/kraken.py
Labels: bug: module

#2110 Picard: directly support Sentieon
  CHANGELOG.md
  CSP.txt
  docs/modules/picard.md
  multiqc/modules/base_module.py
  multiqc/modules/biobambam2/biobambam2.py
  multiqc/modules/picard/AlignmentSummaryMetrics.py
  multiqc/modules/picard/BaseDistributionByCycleMetrics.py
  multiqc/modules/picard/CollectIlluminaBasecallingMetrics.py
  multiqc/modules/picard/CollectIlluminaLaneMetrics.py
  multiqc/modules/picard/CrosscheckFingerprints.py
  multiqc/modules/picard/ExtractIlluminaBarcodes.py
  multiqc/modules/picard/GcBiasMetrics.py
  multiqc/modules/picard/HsMetrics.py
  multiqc/modules/picard/IlluminaBasecallingMetrics.py
  multiqc/modules/picard/IlluminaLaneMetrics.py
  multiqc/modules/picard/InsertSizeMetrics.py
  multiqc/modules/picard/MarkDuplicates.py
  multiqc/modules/picard/MarkIlluminaAdapters.py
  multiqc/modules/picard/OxoGMetrics.py
  multiqc/modules/picard/QualityByCycleMetrics.py
  multiqc/modules/picard/QualityScoreDistributionMetrics.py
  multiqc/modules/picard/QualityYieldMetrics.py
  multiqc/modules/picard/RnaSeqMetrics.py
  multiqc/modules/picard/RrbsSummaryMetrics.py
  multiqc/modules/picard/TargetedPcrMetrics.py
  multiqc/modules/picard/ValidateSamFile.py
  multiqc/modules/picard/VariantCallingMetrics.py
  multiqc/modules/picard/WgsMetrics.py
  multiqc/modules/picard/picard.py
  multiqc/modules/picard/util.py
  multiqc/modules/sentieon/AlignmentSummaryMetrics.py
  multiqc/modules/sentieon/GcBiasMetrics.py
  multiqc/modules/sentieon/InsertSizeMetrics.py
  multiqc/modules/sentieon/__init__.py
  multiqc/modules/sentieon/sentieon.py
  multiqc/templates/default/assets/js/multiqc_tables.js
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: needs-review, module: enhancement

#2174 Fix logging spillover
  CHANGELOG.md
  multiqc/modules/bbduk/bbduk.py
  multiqc/modules/biscuit/biscuit.py
  multiqc/modules/busco/busco.py
  multiqc/modules/cutadapt/cutadapt.py
  multiqc/modules/dragen/overall_mean_cov.py
  multiqc/modules/featureCounts/feature_counts.py
  multiqc/modules/homer/tagdirectory.py
  multiqc/modules/interop/interop.py
  multiqc/modules/qorts/qorts.py
  multiqc/modules/qualimap/QM_BamQC.py
  multiqc/modules/vep/vep.py
  multiqc/utils/mqc_colour.py
  multiqc/utils/report.py
Labels: bug: core, needs-review

#2179 Kaiju: fix "division by zero"
  .github/workflows/changelog.py
  CHANGELOG.md
  multiqc/modules/kaiju/kaiju.py
Labels: priority: high, bug: module, awaits-review

#2183 Try find config in `~/.config` or `$XDG_CONFIG_HOME`
  CHANGELOG.md
  docs/core/getting_started/config.md
  multiqc/utils/config.py
Labels: core: back end

#2178 Config with environment variables, and config strict typing
  CHANGELOG.md
  docs/core/getting_started/config.md
  multiqc/modules/fgbio/ErrorRateByReadPosition.py
  multiqc/multiqc.py
  multiqc/utils/config.py
  multiqc/utils/util_functions.py
  setup.py
Labels: core: back end, awaits-review

#2181 Sample name cleaning with pairs of input filenames
  .gitignore
  CHANGELOG.md
  docs/core/getting_started/config.md
  multiqc/modules/base_module.py
  multiqc/modules/cutadapt/cutadapt.py
  multiqc/modules/fastp/fastp.py
  multiqc/modules/trimmomatic/trimmomatic.py
Labels: core: back end, awaits-review

#2176 Unspecified `"scale"` in table headers defaults to `False`
  CHANGELOG.md
  multiqc/modules/anglerfish/anglerfish.py
  multiqc/modules/clusterflow/clusterflow.py
  multiqc/modules/dragen/trimmer_metrics.py
  multiqc/modules/interop/interop.py
  multiqc/modules/ngsderive/ngsderive.py
  multiqc/modules/qc3C/qc3C.py
  multiqc/modules/whatshap/whatshap.py
  multiqc/plots/table.py
  multiqc/plots/table_object.py
  multiqc/utils/mqc_colour.py
Labels: core: back end, awaits-review

#2189 Fix `"square": True` for scatter plot. Make the GATK BaseRecalibrator plot square
  CHANGELOG.md
  CSP.txt
  multiqc/modules/gatk/base_recalibrator.py
  multiqc/plots/scatter.py
  multiqc/templates/default/assets/js/multiqc_plotting.js
Labels: core: front end, awaits-review, module: enhancement

#2191 `table_columns_visible` and `table_columns_name`: support flat config and `table_id` as a group
  CHANGELOG.md
  docs/core/reports/customisation.md
  multiqc/modules/quast/quast.py
  multiqc/plots/table_object.py
Labels: core: back end, awaits-review

#1666 Upgrade jQuery tablesorter plugin to v2
  CHANGELOG.md
  CSP.txt
  multiqc/templates/default/assets/css/default_multiqc.css
  multiqc/templates/default/assets/js/packages/jquery.tablesorter.min.js
Labels: core: front end, awaits-review

#1667 Allow specifying default sort columns for tables
  CHANGELOG.md
  docs/core/development/plots.md
  multiqc/plots/table.py
  multiqc/plots/table_object.py
Labels: core: front end, awaits-review

#2194 Fix docs URL to spack [skip changelog]
  docs/core/getting_started/installation.md
Labels: documentation

#2197 BCLConvert: fix mean quality, fix count-per-lane barplot
  CHANGELOG.md
  multiqc/modules/bclconvert/bclconvert.py
Labels: bug: module, awaits-review

#2202 Re-add `run()` into the `multiqc` namespace
  CHANGELOG.md
  multiqc/__init__.py
Labels: bug: core
