Repository MultiQC/MultiQC, pull requests merged in 2023-09, with the labels that each got.

#2030 File search: fix off-by-1 error in num_lines
  multiqc/utils/report.py
Labels: first-approval

#2037 Append `namespace` in general stats to the module name
  CHANGELOG.md
  multiqc/modules/base_module.py
  multiqc/modules/bcftools/stats.py
  multiqc/modules/cellranger/_utils.py
  multiqc/modules/cellranger/count.py
  multiqc/modules/cellranger/vdj.py
  multiqc/modules/dragen/coverage_metrics.py
  multiqc/modules/dragen/dragen_gc_metrics.py
  multiqc/modules/dragen/mapping_metrics.py
  multiqc/modules/dragen/vc_metrics.py
  multiqc/modules/dragen_fastqc/gc_metrics.py
  multiqc/modules/hicpro/hicpro.py
  multiqc/modules/homer/findpeaks.py
  multiqc/modules/homer/tagdirectory.py
  multiqc/modules/quast/quast.py
  multiqc/plots/table.py
Labels: first-approval

#1812 New module: sourmash compare
  CHANGELOG.md
  docs/modules/sourmash.md
  multiqc/modules/sourmash/__init__.py
  multiqc/modules/sourmash/compare.py
  multiqc/modules/sourmash/sourmash.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: first-approval

#2020 Qualimap: BamQC: add percentage on target
  CHANGELOG.md
  multiqc/modules/qualimap/QM_BamQC.py
Labels: first-approval

#2048 Fix circular imports in `software_versions`
  multiqc/modules/profile_runtime.py
  multiqc/modules/software_versions.py
  multiqc/multiqc.py
  multiqc/utils/software_versions.py
Labels: refactoring

#2056 Bcftools: fix parsing of multi-sample stats outputs
  CHANGELOG.md
  multiqc/modules/bcftools/stats.py
Labels: first-approval

#2054 Fix casing in software versions table
  multiqc/modules/base_module.py
  multiqc/modules/software_versions.py
  multiqc/templates/default/content.html
  multiqc/utils/software_versions.py
Labels: first-approval

#2055 Don't sys.exit from run() function
  CHANGELOG.md
  multiqc/multiqc.py
Labels: core: back end

#1816 New module: sourmash gather
  docs/modules/sourmash.md
  multiqc/modules/sourmash/gather.py
  multiqc/modules/sourmash/sourmash.py
  multiqc/utils/search_patterns.yaml
Labels: first-approval

#2060 Parametrize top-n categories for Kraken and Sourmash Gather
  CHANGELOG.md
  docs/modules/kraken.md
  docs/modules/sourmash.md
  multiqc/modules/kraken/kraken.py
  multiqc/modules/sourmash/gather.py
Labels: module: change

#2058 Fixed the DOI exports
  CHANGELOG.md
  multiqc/multiqc.py
  multiqc/utils/report.py
Labels: core: bug

#2057 Modules should handle any input. Fix `Preseq` and `BCL Convert` on mixed input
  CHANGELOG.md
  docs/modules/bclconvert.md
  multiqc/modules/bclconvert/bclconvert.py
  multiqc/modules/preseq/preseq.py
Labels: module: change

#2064 Fix table color scaling with negative numbers
  CHANGELOG.md
  multiqc/utils/mqc_colour.py
Labels: first-approval

#2051 Software Versions: Add support to all modules
  multiqc/modules/adapterRemoval/adapterRemoval.py
  multiqc/modules/anglerfish/anglerfish.py
  multiqc/modules/bakta/bakta.py
  multiqc/modules/bbduk/bbduk.py
  multiqc/modules/bcftools/stats.py
  multiqc/modules/bismark/bismark.py
  multiqc/modules/busco/busco.py
  multiqc/modules/cellranger/count.py
  multiqc/modules/cellranger/vdj.py
  multiqc/modules/clipandmerge/clipandmerge.py
  multiqc/modules/cutadapt/cutadapt.py
  multiqc/modules/damageprofiler/damageprofiler.py
  multiqc/modules/dedup/dedup.py
  multiqc/modules/diamond/diamond.py
  multiqc/modules/eigenstratdatabasetools/eigenstratdatabasetools.py
  multiqc/modules/fastq_screen/fastq_screen.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/flash/flash.py
  multiqc/modules/flexbar/flexbar.py
  multiqc/modules/gffcompare/gffcompare.py
  multiqc/modules/gopeaks/gopeaks.py
  multiqc/modules/hifiasm/hifiasm.py
  multiqc/modules/interop/interop.py
  multiqc/modules/longranger/longranger.py
  multiqc/modules/macs2/macs2.py
  multiqc/modules/malt/malt.py
  multiqc/modules/mirtop/mirtop.py
  multiqc/modules/mtnucratio/mtnucratio.py
  multiqc/modules/multivcfanalyzer/multivcfanalyzer.py
  multiqc/modules/pangolin/pangolin.py
  multiqc/modules/purple/purple.py
  multiqc/modules/pycoqc/pycoqc.py
  multiqc/modules/qc3C/qc3C.py
  multiqc/modules/salmon/salmon.py
  multiqc/modules/sambamba/markdup.py
  multiqc/modules/samtools/stats.py
Labels: first-approval

#2062 NanoStat: module clean-up by @schorlton
  docs/modules/nanostat.md
  multiqc/modules/nanostat/nanostat.py
Labels: first-approval, module: enhancement

#2068 Fix bug parsing TSV/CSV custom content
  multiqc/modules/custom_content/custom_content.py
Labels: custom-content

#2069 Fix BamQC GC color scheme, show warning about categorical scale for sequential values
  .gitignore
  docs/core/development/modules.md
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/odgi/odgi.py
  multiqc/modules/qualimap/QM_BamQC.py
  multiqc/plots/table.py
  multiqc/utils/mqc_colour.py
Labels: core: bug

#2025 Add action to populate the change log from PR titles triggered by `@multiqc-bot changelog`
  .github/workflows/changelog.py
  .github/workflows/changelog.yml
  docs/core/development/modules.md
Labels: first-approval, core: infrastructure

#2080 Changelog action: remove `.capitalize()`, add changelog entry
  .github/workflows/changelog.py
  CHANGELOG.md
Labels: core: infrastructure

#2075 FastQC: add top overrepresented sequences table
  .github/workflows/fix-linting.yml
  CHANGELOG.md
  docs/core/development/plots.md
  docs/modules/fastqc.md
  multiqc/modules/fastqc/fastqc.py
Labels: first-approval, module: enhancement

#2083 Picard: fix parsing mixed strings/numbers, account for trailing tab
  CHANGELOG.md
  multiqc/modules/picard/MarkDuplicates.py
Labels: module: bug, first-approval
