Repository MultiQC/MultiQC, pull requests merged in 2023-12, with the labels that each got.

#2208 Custom content plot: do not assume first row are samples
  .github/workflows/changelog.py
  CHANGELOG.md
  multiqc/modules/custom_content/custom_content.py
Labels: core: back end, custom-content, awaits-review

#2212 Fix running `--no-report`
  .github/workflows/multiqc.yml
  CHANGELOG.md
  multiqc/multiqc.py
Labels: awaits-review

#2211 When trying indexing lists/dicts while accessing config parameters, catch TypeError as well
  CHANGELOG.md
  multiqc/plots/boxplot.py
  multiqc/plots/linegraph.py
  multiqc/plots/scatter.py
Labels: core: back end, awaits-review

#2207 Qualimap: BamQC: fix for global-only stats
  CHANGELOG.md
  multiqc/modules/qualimap/QM_BamQC.py
Labels: bug: module, awaits-review

#2210 Bar graphs: add `sort_samples: false` config option, also do not sort `OrderedDict` data
  CHANGELOG.md
  docs/core/development/plots.md
  multiqc/plots/bargraph.py
Labels: core: back end, awaits-review

#2229 DeepTools: Handle missing data in plotProfile
  CHANGELOG.md
  multiqc/modules/deeptools/plotProfile.py
Labels: priority: high, bug: module, awaits-review

#2230 Kraken: fix `UnboundLocalError`
  CHANGELOG.md
  multiqc/modules/kraken/kraken.py
Labels: bug: module, awaits-review

#2226 Picard: more search patterns for MarkDuplicates
  CHANGELOG.md
  multiqc/utils/search_patterns.yaml
Labels: bug: module, awaits-review

#2228 Add missing table `id` in DRAGEN modules, require them in linting
  CHANGELOG.md
  multiqc/modules/bamtools/stats.py
  multiqc/modules/bcftools/stats.py
  multiqc/modules/cellranger/count.py
  multiqc/modules/cellranger/vdj.py
  multiqc/modules/deeptools/bamPEFragmentSizeTable.py
  multiqc/modules/deeptools/estimateReadFiltering.py
  multiqc/modules/deeptools/plotCoverage.py
  multiqc/modules/dragen/coverage_metrics.py
  multiqc/modules/dragen/dragen_gc_metrics.py
  multiqc/modules/dragen/mapping_metrics.py
  multiqc/modules/dragen/sc_atac_metrics.py
  multiqc/modules/dragen/sc_rna_metrics.py
  multiqc/modules/dragen/trimmer_metrics.py
  multiqc/modules/dragen/vc_metrics.py
  multiqc/modules/happy/happy.py
  multiqc/modules/kat/kat.py
  multiqc/modules/picard/ValidateSamFile.py
  multiqc/modules/qc3C/qc3C.py
  multiqc/modules/whatshap/whatshap.py
  multiqc/modules/xengsort/xengsort.py
  multiqc/modules/xenome/xenome.py
  multiqc/plots/table.py
  multiqc/plots/table_object.py
Labels: bug: core, awaits-review

#2235 Update num_lines for fastp search
  multiqc/utils/search_patterns.yaml
Labels: bug: module

#2234 Changelog CI: fix detection of changed module
  .github/workflows/changelog.py
  CHANGELOG.md
Labels: awaits-review, core: infrastructure

#1485 Salmon reports library info to General Stats table
  CHANGELOG.md
  docs/modules/salmon.md
  multiqc/modules/salmon/salmon.py
  multiqc/utils/search_patterns.yaml
Labels: module: enhancement

#2233 `HiC-Pro`: missing search patterns and better handling of missing data
  CHANGELOG.md
  multiqc/modules/hicpro/hicpro.py
  multiqc/utils/search_patterns.yaml
Labels: module: change, awaits-review

#2253 BclConvert: fix duplicated `yield` for 3.9.3+ when the yield is provided explicitly in Quality_Metrics
  CHANGELOG.md
  multiqc/modules/bclconvert/bclconvert.py
Labels: bug: module
