Repository MultiQC/MultiQC, pull requests merged in 2024-10, with the labels that each got.

#2899 Small config validation improvements
  .github/workflows/integration_test.yml
  .github/workflows/unit_tests.yml
  multiqc/base_module.py
  multiqc/core/exec_modules.py
  multiqc/interactive.py
  multiqc/modules/custom_content/custom_content.py
  multiqc/multiqc.py
  multiqc/plots/table_object.py
  multiqc/validation.py
  tests/conftest.py
  tests/test_custom_content.py
  tests/test_plots.py
Labels: core: back end

#2901 Fix generalstats headers key name in documentation
  docs/markdown/custom_content/index.md
  multiqc/modules/custom_content/custom_content.py
Labels: documentation, custom-content

#2854 ngsbits: add submodule samplegender
  multiqc/modules/ngsbits/mappingqc.py
  multiqc/modules/ngsbits/ngsbits.py
  multiqc/modules/ngsbits/readqc.py
  multiqc/modules/ngsbits/samplegender.py
  multiqc/modules/ngsbits/tests/__init__.py
  multiqc/modules/ngsbits/tests/test_samplegender.py
  multiqc/modules/ngsbits/utils.py
  multiqc/search_patterns.yaml
Labels: module: enhancement

#2905 Samtools: Add insert size to general stats table
  multiqc/modules/samtools/stats.py
Labels: module: enhancement

#2911 Fix table CSV export where title contains a comma
  multiqc/modules/rsem/rsem.py
  multiqc/templates/default/assets/js/plots/violin.js
Labels: core: front end

#2912 Docs: fix the Jupyter example link
  docs/markdown/usage/scripts.md
Labels: documentation

#2913 Fix `config.prepend_dirs` or `-d -dd 1`
  docs/markdown/development/modules.md
  multiqc/base_module.py
  multiqc/modules/bamdst/bamdst.py
  multiqc/modules/deeptools/plotCorrelation.py
  multiqc/modules/ganon/ganon.py
  multiqc/modules/hicpro/hicpro.py
  multiqc/modules/hostile/hostile.py
  multiqc/modules/ngsbits/tests/__init__.py
  multiqc/modules/ngsbits/tests/test_samplegender.py
  multiqc/modules/preseq/preseq.py
  multiqc/modules/samtools/tests/test_flagstat.py
  multiqc/modules/sequali/sequali.py
  multiqc/modules/seqwho/seqwho.py
  multiqc/modules/umicollapse/umicollapse.py
  multiqc/modules/umitools/umitools.py
  multiqc/modules/whatshap/whatshap.py
  tests/test_sample_name_cleaning.py
Labels: bug: core

#2920 Sample grouping fixes
  .github/workflows/mypy.yml
  multiqc/modules/custom_content/custom_content.py
  multiqc/plots/plotly/table.py
  multiqc/report.py
  multiqc/templates/default/assets/css/default_multiqc.css
Labels: core: back end

#2922 Fix `cond_formatting_rules` type hint
  multiqc/config.py
  multiqc/plots/table_object.py
Labels: bug: core

#2935 File line block iterator: fix reading long lines that do not fit one…
  multiqc/report.py
Labels: core: back end

#2936 Cutadapt: fix for null values from r2 data
  multiqc/modules/cutadapt/cutadapt.py
Labels: bug: module

#2937 Qualimap: fix parsing ∞ value
  multiqc/modules/qualimap/__init__.py
Labels: bug: module

#2938 Document use of display to show plots in notebooks
  docs/markdown/usage/scripts.md
Labels: documentation

#2939 Custom content image: support custom_data config with section name etc, fix misleading logging
  multiqc/modules/custom_content/custom_content.py
Labels: custom-content

#2934 nanoq: Change lineplots for barplots
  multiqc/modules/nanoq/nanoq.py
Labels: module: enhancement

#2941 Sample grouping: workaround for Safari missing visibility: collapse
  multiqc/templates/default/assets/css/default_multiqc.css
Labels: core: front end
