Repository MultiQC/MultiQC, pull requests merged in 2024-11, with the labels that each got.

#2953 Fix Docker CI for forks: skip login step
  .github/workflows/docker.yml
Labels: core: infrastructure

#2954 Avoid showing `section_comment` both for module and section when they have the same ID (that is, in custom content)
  multiqc/base_module.py
Labels: custom-content

#2955 Configure `custom_table_header_config`: fix docs, support both the old and the new ways
  docs/markdown/reports/customisation.md
  multiqc/plots/table_object.py
Labels: custom-content

#2946 Qualimap: Clarify the direction of the transcript in coverage plot
  multiqc/modules/qualimap/QM_RNASeq.py
Labels: module: enhancement

#2956 Table scatter mini-plots: fix rounding and range
  multiqc/templates/default/assets/js/tables.js
Labels: core: front end

#2957 Fix `plot_type: violin` in custom content
  multiqc/modules/custom_content/custom_content.py
Labels: custom-content

#2958 Build Docker image in PRs
  .dockerignore
  .github/workflows/docker.yml
  Dockerfile
Labels: core: infrastructure

#2885 picard: Add table with all metrics to VariantCallingMetrics section
  multiqc/modules/picard/VariantCallingMetrics.py
Labels: module: enhancement

#2961 Nanostat: add general stats columns
  multiqc/modules/nanostat/nanostat.py
Labels: module: enhancement

#2962 Docker build: add workflow_dispatch, do not push on pull_request
  .github/workflows/docker.yml
Labels: core: infrastructure

#2963 Pin kaleido to 0.2.1 (0.4.1 requires external browser)
  pyproject.toml
Labels: core: back end

#2933 Add module Haplocheck
  multiqc/config_defaults.yaml
  multiqc/modules/haplocheck/__init__.py
  multiqc/modules/haplocheck/haplocheck.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new, waiting: changes

#2965 bcl2fastq: fix missing `R1_*`/`R2_*` metrics
  multiqc/modules/bcl2fastq/bcl2fastq.py
Labels: bug: module

#2967 featurecounts: missing section name and anchor
  multiqc/modules/featurecounts/featurecounts.py
Labels: bug: module

#2968 Violin: add dt to Dataset objects instead of main_table_dt
  multiqc/plots/plotly/violin.py
  multiqc/report.py
Labels: core: refactoring

#2976 bclconvert: fix undetermined barcodes plot
  multiqc/modules/bclconvert/bclconvert.py
Labels: bug: module, module: enhancement

#2988 Dedup: more specific search pattern
  multiqc/search_patterns.yaml
Labels: module: enhancement

#2989 QualiMap BamQC: add dup rate, Ns, mapped paired reads
  multiqc/modules/qualimap/QM_BamQC.py
Labels: module: enhancement

#2985 Change heading in the changelog
  scripts/print_changelog.py
Labels: documentation

#2993 Workflow to sync changelog with Seqera docs
  .github/workflows/seqera_docs_changelog.py
  .github/workflows/seqera_docs_changelog.yml
  CHANGELOG.md
Labels: core: infrastructure

#2994 Fix docker build: remove docs from `.dockerignore`
  .dockerignore
Labels: core: infrastructure

#2995 Interop: remove % suffix for nan values
  multiqc/modules/interop/interop.py
Labels: module: change
