Repository MultiQC/MultiQC, pull requests merged in 2024-04, with the labels that each got.

#2477 Bamdst: fix when `chromosomes.report` is not provided
  multiqc/modules/bamdst/bamdst.py
Labels: bug: module

#2473 Picard WgsMetrics: coverage plot: show % based ≥x, not >x
  multiqc/modules/picard/WgsMetrics.py
Labels: module: change

#2472 Nonpareil: fix data label
  multiqc/modules/nonpareil/nonpareil.py
Labels: module: change

#2489 Fix export plots with `--export` and always export data
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/scatter.py
Labels: bug: core

#2488 Mosdepth: fix absolute coverage plot
  multiqc/modules/mosdepth/mosdepth.py
Labels: bug: module

#2486 FastQC: add option to ignore FastQC quality thresholds
  docs/modules/fastqc.md
  multiqc/modules/dragen_fastqc/assets/js/multiqc_dragen_fastqc.js
  multiqc/modules/fastqc/assets/js/multiqc_fastqc.js
  multiqc/modules/fastqc/fastqc.py
Labels: module: enhancement

#2460 Exclude plot data for sections in `remove_sections`
  multiqc/modules/base_module.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/picard/ValidateSamFile.py
  multiqc/multiqc.py
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/box.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/scatter.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
  multiqc/templates/default/content.html
Labels: core: refactoring

#2490 Do not attempt to render flat plot when no data
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/violin.py
Labels: bug: core

#2445 Add type hints to report module
  multiqc/utils/report.py
  multiqc/utils/util_functions.py
Labels: core: refactoring

#2446 Break up the main run function
  multiqc/multiqc.py
  multiqc/utils/config.py
  multiqc/utils/config_defaults.yaml
Labels: core: refactoring

#2457 Use Rich console for logging
  multiqc/utils/log.py
  multiqc/utils/report.py
  pyproject.toml
Labels: core: refactoring

#2496 DRAGEN: add ploidy estimation table
  multiqc/modules/dragen/ploidy_estimation_metrics.py
Labels: module: enhancement

#2502 qc3C: fix detecting sname for relative path
  multiqc/modules/qc3C/qc3C.py
Labels: bug: module

#2510 Stream json data to a file to save 30% of the memory.
  multiqc/multiqc.py
  multiqc/utils/report.py
  multiqc/utils/util_functions.py
Labels: core: back end

#2506 Sort filepatterns for faster searching
  multiqc/utils/report.py
Labels: core: back end

#2504 Use gzip rather than lzstring for compression and decompression of the plot data
  .gitignore
  multiqc/templates/default/assets/js/decompress.js
  multiqc/templates/default/assets/js/packages/lz-string.min.js
  multiqc/templates/default/assets/js/packages/pako_inflate.min.js
  multiqc/templates/default/assets/js/plotting.js
  multiqc/templates/default/includes.html
  multiqc/utils/lzstring.py
  multiqc/utils/report.py
Labels: core: back end

#2513 Search file blocks rather than individual lines for faster results
  multiqc/utils/report.py
Labels: core: back end

#2516 Reduce Sequali and (slightly) FastQC memory footprint
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/sequali/sequali.py
Labels: module: enhancement
