Repository MultiQC/MultiQC, pull requests merged in 2024-05, with the labels that each got.

#2511 bclconvert: fix for absent index reads
  multiqc/modules/bclconvert/bclconvert.py
Labels: bug: module

#2526 Bclconvert: show message when no undetermined reads instead of error
  multiqc/modules/bclconvert/bclconvert.py
  multiqc/plots/plotly/bar.py
Labels: module: enhancement

#2525 Cellranger: fix parsing antibody tab without `antibody_treemap_plot`
  multiqc/modules/cellranger/count.py
Labels: bug: module

#2515 Reduce memory requirement of MultiQC main functions
  multiqc/multiqc.py
  multiqc/plots/plotly/plot.py
  multiqc/utils/report.py
  multiqc/utils/util_functions.py
Labels: core: back end

#2528 Cutadapt: Speed up module by caching parsing versions
  multiqc/modules/cutadapt/cutadapt.py
Labels: core: back end

#2501 New module: Hostile
  docs/modules/hostile.md
  multiqc/modules/hostile/__init__.py
  multiqc/modules/hostile/hostile.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  pyproject.toml
Labels: module: new, waiting: response

#2529 Do replace_nan in place rather than creating a new object
  multiqc/utils/util_functions.py
Labels: core: back end

#2532 Fix loading FastQC JS (broken after introducing async decompression)
  multiqc/modules/dragen_fastqc/assets/js/multiqc_dragen_fastqc.js
  multiqc/modules/fastqc/assets/js/multiqc_fastqc.js
  multiqc/multiqc.py
  multiqc/templates/default/assets/js/decompress.js
  multiqc/templates/default/assets/js/load.js
  multiqc/templates/default/assets/js/multiqc.js
  multiqc/templates/default/assets/js/plotting.js
  multiqc/templates/default/includes.html
Labels: core: back end

#2536 Fastp: when could not parse sample name from command (i.e. stdin), use filename and proceed
  multiqc/modules/fastp/fastp.py
Labels: bug: module

#2540 Goleft indexcov: work correctly even if no valid contigs
  multiqc/modules/goleft_indexcov/goleft_indexcov.py
Labels: module: enhancement

#2543 Plot config validation: avoid `sys.exit()`, better deprecation messages
  multiqc/core/exceptions.py
  multiqc/core/exec_modules.py
  multiqc/core/init_log.py
  multiqc/modules/custom_content/custom_content.py
  multiqc/multiqc.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
  multiqc/report.py
Labels: core: refactoring

#2542 Deprecate old `multiqc.utils.config` and `multiqc.utils.report`
  multiqc/utils/config.py
  multiqc/utils/report.py
Labels: core: refactoring

#2544 Fix error when using default sort
  multiqc/plots/plotly/table.py
Labels: bug: core

#2546 Use dataclasses for table and violin columns
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
  multiqc/plots/table_object.py
Labels: core: refactoring

#2545 Sequali: allow paired-end data.
  multiqc/modules/sequali/sequali.py
Labels: module: enhancement

#2548 Profile per-module memory and run time, visualize in the profile module
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/exec_modules.py
  multiqc/core/update_config.py
  multiqc/modules/profile_runtime.py
  multiqc/multiqc.py
  multiqc/plots/plotly/bar.py
  multiqc/report.py
Labels: core: back end

#2551 Clean up module raw data after running each module
  multiqc/base_module.py
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/exec_modules.py
  multiqc/core/update_config.py
  multiqc/interactive.py
  multiqc/modules/samtools/samtools.py
Labels: core: back end

#2552 FastQC: Skip per tile sequence quality section for better performance
  multiqc/modules/fastqc/fastqc.py
Labels: core: refactoring

#2538 Interactive usage docs [skip changelog]
  .gitignore
  docs/config.yaml
  docs/core/development/plots.md
  docs/core/getting_started/config.md
  docs/core/usage/interactive.md
  docs/core/usage/troubleshooting.md
  multiqc/interactive.py
  pyproject.toml
Labels: documentation

#2579 Cellranger VDJ: handle missing `vdj_annotation` and `vdj_enrichment`
  multiqc/modules/cellranger/vdj.py
Labels: bug: module

#2581 Quast: underscore attributes captured by lambdas to avoid wiping them after module is finished
  multiqc/modules/quast/quast.py
Labels: bug: module

#2586 Fix links in fgbio.md
  docs/modules/fgbio.md
Labels: documentation

#2599 Fix hiding column with all empty values in custom content
  multiqc/plots/plotly/table.py
Labels: bug: core
