Repository MultiQC/MultiQC, pull requests merged in 2024-03, with the labels that each got.

#2411 Set missing values to None for bbmap qahist
  CHANGELOG.md
  multiqc/modules/bbmap/plot_qahist.py
Labels: bug: module

#2396 Update Clipboard library
  CHANGELOG.md
  CSP.txt
  multiqc/templates/default/assets/js/packages/clipboard.js
  multiqc/templates/default/assets/js/packages/clipboard.min.js
  multiqc/templates/default/assets/js/tables.js
Labels: core: front end

#2254 Samtools: Add support for `markdup`
  CHANGELOG.md
  docs/modules/samtools.md
  multiqc/modules/samtools/markdup.py
  multiqc/modules/samtools/samtools.py
  multiqc/utils/search_patterns.yaml
Labels: module: enhancement

#2425 Remove encoding and shebang headers from module files
  .github/workflows/code_checks.py
  docs/core/development/plugins.md
  multiqc/__init__.py
  multiqc/__main__.py
  multiqc/modules/bracken/bracken.py
  multiqc/modules/flash/flash.py
  multiqc/modules/freyja/freyja.py
  multiqc/modules/gatk/__init__.py
  multiqc/modules/gatk/analyze_saturation_mutagenesis.py
  multiqc/modules/gatk/base_recalibrator.py
  multiqc/modules/gatk/varianteval.py
  multiqc/modules/ivar/ivar.py
  multiqc/modules/mirtrace/mirtrace.py
  multiqc/modules/phantompeakqualtools/phantompeakqualtools.py
  multiqc/modules/profile_runtime.py
  multiqc/modules/samtools/idxstats.py
  multiqc/modules/samtools/stats.py
  multiqc/modules/software_versions.py
  multiqc/modules/sourmash/compare.py
  multiqc/modules/sourmash/gather.py
  multiqc/modules/sourmash/sourmash.py
  multiqc/modules/truvari/bench.py
  multiqc/modules/truvari/truvari.py
  multiqc/modules/varscan2/varscan2.py
  multiqc/multiqc.py
  multiqc/utils/config.py
  multiqc/utils/log.py
  multiqc/utils/megaqc.py
  multiqc/utils/mqc_colour.py
  multiqc/utils/plugin_hooks.py
  multiqc/utils/report.py
  multiqc/utils/software_versions.py
  multiqc/utils/strict_helpers.py
  multiqc/utils/util_functions.py
Labels: core: refactoring

#2429 Spaceranger: fix for missing `genomic_dna` section
  CHANGELOG.md
  multiqc/modules/spaceranger/_utils.py
  multiqc/modules/spaceranger/count.py
Labels: bug: module

#2421 Disable CSP linting, keep the script for users to run manually
  .github/workflows/multiqc.yml
  CHANGELOG.md
  CSP.txt
  multiqc/modules/dragen_fastqc/assets/js/multiqc_dragen_fastqc.js
  multiqc/modules/fastqc/assets/js/multiqc_fastqc.js
  multiqc/modules/rseqc/assets/js/multiqc_rseqc.js
  multiqc/utils/report.py
  scripts/print_missing_csp.py
  test/print_missing_csp.py
Labels: awaits-review, core: infrastructure

#2427 Do not maintain change log between releases
  .github/RELEASE_CHECKLIST.md
  .github/workflows/changelog.py
  .github/workflows/changelog.yml
  CHANGELOG.md
  scripts/print_changelog.py
Labels: awaits-review, core: infrastructure

#2414 Bcftools: Stats: add multialleic sites column
  multiqc/modules/bcftools/stats.py
Labels: awaits-review, module: enhancement

#2430 Violin multiple datasets & samtools flagstat percentage switch
  multiqc/modules/samtools/flagstat.py
  multiqc/modules/samtools/samtools.py
  multiqc/plots/plotly/violin.py
  multiqc/plots/table.py
  multiqc/plots/table_object.py
  multiqc/plots/violin.py
Labels: module: enhancement

#2434 Core module refactoring: declare `mod_cust_config`, add type hints
  multiqc/modules/adapterremoval/__init__.py
  multiqc/modules/base_module.py
  multiqc/modules/custom_content/custom_content.py
  multiqc/multiqc.py
Labels: core: refactoring

#2279 Add `CMD` to `Dockerfile` so a default run without any parameters displays the `--help`
  .dockerignore
  Dockerfile
Labels: awaits-review, core: infrastructure

#2432 Replace `NaN` with `null` in exported JSON
  multiqc/utils/megaqc.py
  multiqc/utils/util_functions.py
Labels: core: back end, awaits-review

#2419 Use native clipboard API
  CHANGELOG.md
  CSP.txt
  multiqc/templates/default/assets/js/packages/clipboard.js
  multiqc/templates/default/assets/js/packages/clipboard.min.js
  multiqc/templates/default/assets/js/tables.js
Labels: core: front end, awaits-review

#2431 QualiMap BamQC: when trimming long tails, keep at least 20x
  multiqc/modules/qualimap/QM_BamQC.py
Labels: awaits-review, module: enhancement

#2413 Allow to set style of line graph (lines or lines+markers) per plot
  docs/core/development/plots.md
  multiqc/plots/plotly/line.py
Labels: core: front end, awaits-review

#2441 New module: Sequali
  docs/modules/sequali.md
  multiqc/modules/sequali/__init__.py
  multiqc/modules/sequali/sequali.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  pyproject.toml
Labels: module: new

#2447 Move Dataset class outside of Plot function, remove Plot dependency [no changelog]
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/box.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/scatter.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
Labels: core: refactoring

#2451 Normalise plot settings: rename `decimalPlaces` to `tt_decimals`
  docs/core/development/plots.md
  multiqc/modules/bamtools/stats.py
  multiqc/modules/bismark/bismark.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/hops/hops.py
  multiqc/modules/ivar/ivar.py
  multiqc/modules/librarian/librarian.py
  multiqc/modules/motus/motus.py
  multiqc/modules/rseqc/bam_stat.py
  multiqc/modules/samtools/stats.py
  multiqc/modules/sourmash/compare.py
  multiqc/modules/vcftools/relatedness2.py
  multiqc/plots/plotly/heatmap.py
Labels: core: refactoring

#2454 Picard CorsscheckFingerprints: support multiple files
  multiqc/modules/picard/CrosscheckFingerprints.py
Labels: bug: module

#2455 Fix accidental leftover modify lambda in JSON dump
  multiqc/plots/plotly/violin.py
Labels: bug: core

#2453 Busco: fix barplot colors
  multiqc/plots/plotly/bar.py
  multiqc/templates/default/assets/js/plots/bar.js
Labels: bug: module

#2456 BclConvert: add all file types to sources
  multiqc/modules/bclconvert/bclconvert.py
Labels: bug: module

#2462 FastQC: fix ZeroDivisionError error
  multiqc/modules/fastqc/fastqc.py
Labels: bug: module

#2465 Document line graph categories [skip changelog]
  docs/core/development/plots.md
Labels: documentation
