Repository MultiQC/MultiQC, pull requests merged in 2024-06, with the labels that each got.

#2604 Fix disabling `sort_rows` in custom content: subclass `TableConfig` from `ValidatedConfig` and use deprecated
  CHANGELOG.md
  multiqc/core/exec_modules.py
  multiqc/core/write_results.py
  multiqc/modules/custom_content/custom_content.py
  multiqc/modules/damageprofiler/damageprofiler.py
  multiqc/modules/mapdamage/mapdamage.py
  multiqc/modules/pbmarkdup/pbmarkdup.py
  multiqc/modules/vep/vep.py
  multiqc/modules/whatshap/whatshap.py
  multiqc/multiqc.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/table_object.py
  multiqc/report.py
  multiqc/validation.py
Labels: bug: core

#2610 Fix `re_contents` search patterns when pattern is in the middle of the file - naive
  multiqc/report.py
  multiqc/search_patterns.yaml
Labels: bug: core

#2614 UMI-tools extract module: Improve plots
  multiqc/modules/umitools/umitools.py
Labels: module: enhancement

#2615 Flat plot legend tweaks
  docs/core/getting_started/config.md
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/modules/fastqc/fastqc.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
Labels: module: enhancement

#2617 Salmon: fix ignored parsed `library_types` when its type is list
  multiqc/modules/salmon/salmon.py
Labels: bug: module

#2618 DRAGEN vc_metrics: pre-filter numbers can be zero
  multiqc/modules/dragen/vc_metrics.py
Labels: dragen

#2573 Pydantic model `Series` for line plot data and `extra_series`
  multiqc/core/write_results.py
  multiqc/modules/deeptools/plotProfile.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/nonpareil/nonpareil.py
  multiqc/modules/preseq/preseq.py
  multiqc/modules/qualimap/QM_BamQC.py
  multiqc/plots/linegraph.py
  multiqc/plots/plotly/line.py
  multiqc/validation.py
Labels: core: refactoring

#2626 Resolve inconsistent non-optical pair duplicate variable name in samtools markdup module
  multiqc/modules/samtools/markdup.py
Labels: bug: module

#2629 DRAGEN: fix gc_metrics submodule
  multiqc/modules/dragen/dragen_gc_metrics.py
Labels: bug: module

#2628 Fix Incorrect Calculation of % Q30 Bases
  multiqc/modules/bbmap/bbmap.py
Labels: bug: module

#2624 Module unit tests
  .github/workflows/fix_linting.yml
  .github/workflows/integration_tests.yml
  .github/workflows/lint_code.yml
  .github/workflows/unit_tests.yml
  multiqc/modules/biobambam2/biobambam2.py
  multiqc/modules/ccs/tests/__init__.py
  multiqc/modules/ccs/tests/test_ccs.py
  multiqc/modules/dragen/coverage_metrics.py
  multiqc/modules/dragen/dragen.py
  multiqc/modules/dragen/overall_mean_cov.py
  multiqc/modules/dragen/tests/__init__.py
  multiqc/modules/dragen/tests/test_dragen.py
  multiqc/modules/dragen/utils.py
  multiqc/modules/picard/AlignmentSummaryMetrics.py
  multiqc/modules/picard/BaseDistributionByCycleMetrics.py
  multiqc/modules/picard/CrosscheckFingerprints.py
  multiqc/modules/picard/ExtractIlluminaBarcodes.py
  multiqc/modules/picard/GcBiasMetrics.py
  multiqc/modules/picard/HsMetrics.py
  multiqc/modules/picard/IlluminaBasecallingMetrics.py
  multiqc/modules/picard/IlluminaLaneMetrics.py
  multiqc/modules/picard/InsertSizeMetrics.py
  multiqc/modules/picard/MarkDuplicates.py
  multiqc/modules/picard/MarkIlluminaAdapters.py
  multiqc/modules/picard/OxoGMetrics.py
  multiqc/modules/picard/QualityByCycleMetrics.py
  multiqc/modules/picard/QualityScoreDistributionMetrics.py
  multiqc/modules/picard/QualityYieldMetrics.py
  multiqc/modules/picard/RnaSeqMetrics.py
  multiqc/modules/picard/RrbsSummaryMetrics.py
  multiqc/modules/picard/TargetedPcrMetrics.py
  multiqc/modules/picard/ValidateSamFile.py
  multiqc/modules/picard/VariantCallingMetrics.py
  multiqc/modules/picard/WgsMetrics.py
  multiqc/modules/picard/picard.py
  multiqc/modules/picard/tests/__init__.py
  multiqc/modules/picard/tests/test_picard.py
  multiqc/modules/samtools/tests/__init__.py
  multiqc/modules/samtools/tests/test_flagstat.py
  multiqc/plots/table_object.py
  multiqc/report.py
  multiqc/search_patterns.yaml
  multiqc/utils/testing.py
  multiqc/validation.py
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/core/test_get_filelist.py
  tests/core/test_interactive.py
  tests/test_interactive.py
  tests/test_modules_run.py
  tests/test_plots.py
  tests/test_sample_name_cleaning.py
  tests/test_search_files.py
Labels: core: refactoring, core: infrastructure

#2645 Nanostat: support different Q cutoffs
  multiqc/modules/nanostat/nanostat.py
Labels: module: enhancement

#2648 Plot config validation: validate x_lines, x_bands, etc
  multiqc/plots/plotly/line.py
  multiqc/validation.py
Labels: custom-content

#2654 Fix custom content submodules with config
  multiqc/config.py
  multiqc/core/file_search.py
  multiqc/modules/custom_content/custom_content.py
Labels: custom-content

#2661 Fix `bbmap/qchist` search pattern
  multiqc/search_patterns.yaml
Labels: bug: module

#2657 Fix parsing kraken vs. bracken: respect `num_lines` in search patterns
  multiqc/report.py
  multiqc/search_patterns.yaml
Labels: bug: module

#2663 Picard HsMetrics: Support any custom X coverage metrics
  multiqc/modules/picard/HsMetrics.py
Labels: module: enhancement
