Repository MultiQC/MultiQC, pull requests merged in 2024-12, with the labels that each got.

#2999 Naturally sort bar graph samples
  multiqc/plots/bargraph.py
Labels: core: front end

#3001 Save toolbox settings automatically and to file
  multiqc/templates/default/assets/js/toolbox.js
  multiqc/templates/default/toolbox.html
Labels: core: front end

#3000 fastp: add overrepresented sequences plot and table
  multiqc/modules/fastp/fastp.py
Labels: module: enhancement

#3006 Document barplot `sort_samples`
  docs/markdown/development/plots.md
Labels: core: front end

#3007 Nanostat new format: fix parsing sample name
  multiqc/modules/nanostat/nanostat.py
Labels: bug: module

#3008 GATK BQSR: support Sentieon QualCal output
  multiqc/modules/gatk/analyze_saturation_mutagenesis.py
  multiqc/modules/gatk/base_recalibrator.py
  multiqc/modules/gatk/gatk.py
  multiqc/modules/gatk/utils.py
  multiqc/modules/gatk/varianteval.py
  multiqc/plots/plotly/violin.py
  multiqc/search_patterns.yaml
Labels: module: enhancement

#2978 Added module Checkm2: Rapid assessment of genome bin quality using machine learning
  multiqc/config_defaults.yaml
  multiqc/modules/checkm2/__init__.py
  multiqc/modules/checkm2/checkm2.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#2990 Add module Checkm: automated method for assessing the quality of a genome using a broader set of marker genes
  multiqc/config_defaults.yaml
  multiqc/modules/checkm/__init__.py
  multiqc/modules/checkm/checkm.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#2970 Add module GTDB-Tk: a software toolkit for assigning objective taxonomic classifications to bacterial and archaeal genomes
  multiqc/config_defaults.yaml
  multiqc/modules/checkm/checkm.py
  multiqc/modules/checkm2/checkm2.py
  multiqc/modules/gtdbtk/__init__.py
  multiqc/modules/gtdbtk/gtdbtk.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#2925 New module: Cell Ranger ARC - adding a new module named Cell Ranger ARC
  multiqc/modules/cellranger_arc/__init__.py
  multiqc/modules/cellranger_arc/cellranger_arc.py
  multiqc/modules/cellranger_arc/tests/__init__.py
  multiqc/modules/cellranger_arc/tests/test_cellranger_arc.py
  multiqc/modules/cellranger_arc/utils.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#3010 Do not preserve `saved_raw_data` in modules, write directly to files instead
  multiqc/base_module.py
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/update_config.py
  multiqc/core/write_results.py
  multiqc/interactive.py
  multiqc/modules/cellranger_arc/tests/test_cellranger_arc.py
  multiqc/modules/picard/util.py
  multiqc/modules/samtools/tests/test_flagstat.py
  multiqc/modules/umicollapse/tests/test_umicollapse.py
  multiqc/modules/umitools/tests/test_umitools.py
  multiqc/plots/plotly/table.py
  multiqc/report.py
  multiqc/utils/megaqc.py
  tests/test_cmdline.py
  tests/test_modules_run.py
Labels: core: back end

#3012 DRAGEN: RNA quant metrics: support forward and reverse fragments in barplot
  multiqc/modules/dragen/rna_quant_metrics.py
  multiqc/modules/dragen/time_metrics.py
Labels: module: enhancement

#2910 Add module telseq: a software that estimates telomere length from whole genome sequencing data (BAMs)
  multiqc/config_defaults.yaml
  multiqc/modules/telseq/__init__.py
  multiqc/modules/telseq/telseq.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#3017 RNA SeqC: more metrics in gen stats
  multiqc/modules/rna_seqc/rna_seqc.py
Labels: module: enhancement

#3018 QualiMap RNASeq: add gen stats columns for exonic, intronic, intergenic, overlapping
  multiqc/modules/qualimap/QM_RNASeq.py
Labels: module: enhancement

#3021 phantompeakqualtools: Adjust minimum value to 1 for NSC coeff
  multiqc/modules/phantompeakqualtools/phantompeakqualtools.py
Labels: module: enhancement

#3022 Sample grouping: add docs example how to group by lane and read type
  docs/markdown/reports/customisation.md
Labels: documentation

#3025 Add Cursor rules for module generation
  .cursorrules
Labels: core: infrastructure

#3024 Pychopper: add UMI barpot
  multiqc/modules/pychopper/pychopper.py
Labels: module: enhancement

#1910 New module: MosaiCatcher
  multiqc/config_defaults.yaml
  multiqc/modules/mosaicatcher/__init__.py
  multiqc/modules/mosaicatcher/mosaicatcher.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#3029 Update ruff to v0.8.3
  .pre-commit-config.yaml
  pyproject.toml
Labels: core: infrastructure

#3011 New module: percolator: a semi-supervised learning framework for peptide identification from shotgun proteomics datasets.
  multiqc/config_defaults.yaml
  multiqc/modules/percolator/__init__.py
  multiqc/modules/percolator/percolator.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#3030 Add pytest ini options to `pyproject.toml`
  pyproject.toml
Labels: core: infrastructure

#3031 Update module docs to use along with `.cursorrules`
  .cursorrules
  docs/markdown/development/modules.md
Labels: documentation, core: infrastructure

#3033 Align order of lineplot categories across samples
  multiqc/modules/mgikit/mgikit.py
  multiqc/modules/mosdepth/mosdepth.py
  multiqc/plots/linegraph.py
Labels: bug: core

#3034 Improve config validation: print path in config, shorten lists in error messages
  .gitignore
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/nonpareil/nonpareil.py
  multiqc/modules/preseq/preseq.py
  multiqc/plots/bargraph.py
  multiqc/plots/linegraph.py
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/box.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/scatter.py
  multiqc/plots/table_object.py
  multiqc/validation.py
  tests/test_custom_content.py
  tests/test_plots.py
Labels: core: back end
