Repository MultiQC/MultiQC, pull requests merged in 2024-09, with the labels that each got.

#2816 Type hint `_template_mod` in plots
  multiqc/config.py
  multiqc/core/exec_modules.py
  multiqc/plots/bargraph.py
  multiqc/plots/box.py
  multiqc/plots/heatmap.py
  multiqc/plots/linegraph.py
  multiqc/plots/scatter.py
  multiqc/plots/table.py
  multiqc/plots/violin.py
  tests/test_search_files.py
Labels: core: refactoring

#2811 Fix a search pattern of Picard CollectRnaSeqMetrics
  multiqc/search_patterns.yaml
Labels: module: enhancement

#2804 Fix applying `exclude_files` in search patterns
  multiqc/report.py
Labels: bug: core

#2817 FastQC: fix calculating average read length
  multiqc/modules/fastqc/fastqc.py
Labels: bug: module

#2814 Add UMICollapse module
  multiqc/config_defaults.yaml
  multiqc/modules/umicollapse/__init__.py
  multiqc/modules/umicollapse/tests/__init__.py
  multiqc/modules/umicollapse/tests/test_umicollapse.py
  multiqc/modules/umicollapse/umicollapse.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new, waiting: example data

#2819 Wrap exporting flat plots in try-catch
  multiqc/plots/plotly/plot.py
Labels: core: back end

#2821 Cellranger: fix data source tag
  multiqc/modules/cellranger/vdj.py
Labels: bug: module

#2818 Prefix table column IDs with namespace, but allow configuration to use both short and long anchors
  multiqc/config.py
  multiqc/core/order_modules_and_sections.py
  multiqc/core/write_results.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
  multiqc/plots/table_object.py
  multiqc/report.py
  tests/test_custom_content.py
Labels: core: refactoring

#2822 Kraken: fix for empty top ranks. Also handle it in bargraph
  multiqc/modules/kraken/kraken.py
  multiqc/plots/bargraph.py
Labels: bug: module

#2823 Picard: fix parsing Sentieon IS metrics
  multiqc/modules/picard/InsertSizeMetrics.py
Labels: bug: module

#2828 When both `contents` and `contents_re` are specified in a search patterns, treat it as logical AND
  docs/core/development/modules.md
  multiqc/report.py
Labels: core: back end

#2829 Fix copy multiqc.log into multiqc_data output folder
  multiqc/core/log_and_rich.py
  multiqc/core/write_results.py
Labels: bug: core

#2834 fastp: support `--merged` flag
  multiqc/modules/fastp/fastp.py
Labels: module: enhancement

#2836 Run plot export in threads with a time out and handle freezes
  multiqc/core/write_results.py
  multiqc/plots/plotly/plot.py
Labels: core: back end

#2838 Ganon: support non-verbose output, fix missing `removed with --min-count`
  multiqc/modules/ganon/ganon.py
  multiqc/search_patterns.yaml
Labels: module: enhancement

#2840 Samtools coverage: suppot `exclude_contigs` and `include_contigs`
  multiqc/modules/mosdepth/mosdepth.py
  multiqc/modules/samtools/coverage.py
  multiqc/modules/samtools/samtools.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
Labels: module: enhancement

#2844 Fix autoselection in plot export toolbox
  multiqc/plots/plotly/plot.py
  multiqc/templates/default/assets/js/toolbox.js
Labels: core: front end

#2845 Fix bar plot export from toolbox
  multiqc/templates/default/assets/js/plots/bar.js
Labels: core: front end

#2846 Add `py.typed` to mark package as providing type information
  multiqc/py.typed
  pyproject.toml
Labels: core: infrastructure

#2848 Use classes for column/row hiding - fixes hiding in expanded groups
  multiqc/templates/default/assets/js/tables.js
Labels: core: front end

#2847 Support boxplot in custom content
  docs/core/custom_content/index.md
  docs/core/development/plots.md
  multiqc/modules/custom_content/custom_content.py
  multiqc/plots/plotly/plot.py
  multiqc/types.py
Labels: custom-content

#2849 Custom content minor fixes
  docs/core/custom_content/index.md
  multiqc/modules/custom_content/custom_content.py
  multiqc/types.py
Labels: custom-content

#2851 Allow `x_band`, `x_lines`, `x_minrange` for any plot type (specifically scatter)
  multiqc/plots/linegraph.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/scatter.py
  multiqc/validation.py
Labels: core: front end

#2852 NanoStat: support multi-sample logs
  multiqc/modules/nanostat/nanostat.py
Labels: module: enhancement

#2856 Fix FASTQC Per Base Sequence Content plot click when module run multiple times
  multiqc/modules/fastqc/assets/js/multiqc_fastqc.js
  multiqc/modules/fastqc/fastqc.py
  multiqc/plots/plotly/heatmap.py
  multiqc/templates/default/assets/js/plotting.js
  multiqc/templates/default/content.html
Labels: bug: module

#2862 Support Python 3.13, drop 3.8
  .github/workflows/deploy_pypi.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/docs_preview.yml
  .github/workflows/fix_linting.yml
  .github/workflows/integration_test.yml
  .github/workflows/lint_code.yml
  .github/workflows/mypy.yml
  .github/workflows/screenshots.yml
  .github/workflows/unit_tests.yml
  .github/workflows/windows.yml
  docs/core/getting_started/installation.md
  multiqc/__init__.py
  pyproject.toml
Labels: core: refactoring

#2865 Check `add_data_source` args (either `path` or `f` should be specified), use `strict_helpers.lint_error`
  multiqc/base_module.py
  multiqc/core/strict_helpers.py
  multiqc/modules/bamdst/bamdst.py
  multiqc/modules/bcl2fastq/bcl2fastq.py
  multiqc/modules/seqera_cli/seqera_cli.py
  tests/test_plots.py
Labels: core: refactoring

#2871 Table sample groups: allow clicking the entire row to expand, add cursor pointer
  multiqc/templates/default/assets/css/default_multiqc.css
  multiqc/templates/default/assets/js/tables.js
Labels: core: front end

#2872 Bclconvert: group samples and lanes, refactor
  CHANGELOG.md
  multiqc/base_module.py
  multiqc/config.py
  multiqc/modules/bcl2fastq/bcl2fastq.py
  multiqc/modules/bclconvert/bclconvert.py
  multiqc/modules/custom_content/custom_content.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/plots/bargraph.py
  multiqc/plots/box.py
  multiqc/plots/heatmap.py
  multiqc/plots/linegraph.py
  multiqc/plots/plotly/__init__.py
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/box.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/scatter.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
  multiqc/plots/scatter.py
  multiqc/plots/table.py
  multiqc/plots/table_object.py
  multiqc/plots/violin.py
  multiqc/report.py
  multiqc/types.py
  multiqc/utils/mqc_colour.py
  multiqc/utils/util_functions.py
  pyproject.toml
Labels: module: enhancement

#2875 Ignore unrecognized custom table fields
  multiqc/plots/table_object.py
Labels: bug: core, custom-content

#2879 Flatten general stats groups into the `multiqc_data.json` for back-compat
  multiqc/report.py
Labels: core: back end

#2880 Picard HsMetrics: fix collecting data sources
  multiqc/modules/picard/HsMetrics.py
  multiqc/modules/picard/util.py
  multiqc/plots/table.py
  multiqc/plots/table_object.py
Labels: bug: module

#2881 Kraken: re-add the Unclassified tab to the Top taxa barplot
  multiqc/modules/kraken/kraken.py
Labels: module: enhancement

#2889 Suppress "SyntaxWarning: invalid escape sequence" warning from `colormath`
  multiqc/__init__.py
Labels: core: infrastructure

#2888 Disable plot export in incompatible architecture containers (when running through rosetta)
  multiqc/plots/plotly/plot.py
  multiqc/validation.py
  pyproject.toml
Labels: core: back end

#2891 Strip out docs machinery, update a lot of links
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/docs_preview.yml
  README.md
  docs/markdown/custom_content/index.md
  docs/markdown/development/modules.md
  docs/markdown/getting_started/config.md
  docs/markdown/modules/bcftools.md
  docs/markdown/modules/bclconvert.md
  docs/markdown/modules/biscuit.md
  docs/markdown/modules/cutadapt.md
  docs/markdown/modules/deeptools.md
  docs/markdown/modules/fastqc.md
  docs/markdown/modules/lima.md
  docs/markdown/modules/preseq.md
  docs/markdown/modules/qualimap.md
  docs/markdown/modules/quast.md
  docs/markdown/modules/supernova.md
  docs/markdown/modules/vcftools.md
  docs/markdown/usage/troubleshooting.md
  multiqc/modules/bcftools/bcftools.py
  multiqc/modules/bclconvert/bclconvert.py
  multiqc/modules/biscuit/biscuit.py
  multiqc/modules/cutadapt/cutadapt.py
  multiqc/modules/deeptools/deeptools.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/lima/lima.py
  multiqc/modules/preseq/preseq.py
  multiqc/modules/profile_runtime.py
  multiqc/modules/qualimap/qualimap.py
  multiqc/modules/quast/quast.py
  multiqc/modules/supernova/supernova.py
  multiqc/modules/vcftools/vcftools.py
  multiqc/multiqc.py
  multiqc/plots/plotly/plot.py
  multiqc/report.py
  multiqc/templates/default/toolbox.html
  preview_docs.sh
  pyproject.toml
Labels: documentation

#2892 Support Python 3.8
  .github/workflows/mypy.yml
  .github/workflows/unit_tests.yml
  multiqc/__init__.py
  pyproject.toml
  scripts/print_changelog.py
Labels: core: infrastructure

#2894 Remove the separate Bracken module as it just uses Kraken internally
  docs/markdown/modules/bracken.md
  docs/markdown/modules/kraken.md
  multiqc/config_defaults.yaml
  multiqc/modules/bracken/__init__.py
  multiqc/modules/bracken/bracken.py
  multiqc/modules/kraken/kraken.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: change

#2895 Kraken: fix minimizers heatmap
  multiqc/modules/kraken/kraken.py
Labels: bug: module
