Repository MultiQC/MultiQC, pull requests merged in 2024-08, with the labels that each got.

#2732 RSeQC: fix duplicateed namespace
  multiqc/modules/rseqc/bam_stat.py
  multiqc/modules/rseqc/inner_distance.py
  multiqc/modules/rseqc/tin.py
Labels: bug: module

#2733 Fix `--pdf` option to generate `multiqc_report.pdf`
  multiqc/core/update_config.py
  multiqc/core/write_results.py
  multiqc/multiqc.py
  multiqc/plots/plotly/plot.py
  multiqc/templates/default/footer.html
  multiqc/templates/simple/footer.html
Labels: bug: core, core: back end, core: front end

#2734 Nonpareil: Update docs about new version that generates the JSON file
  multiqc/modules/nonpareil/nonpareil.py
Labels: module: enhancement

#2739 fix handling of module href str
  multiqc/base_module.py
Labels: bug: core

#2723 New module: nanoq
  multiqc/config_defaults.yaml
  multiqc/modules/nanoq/__init__.py
  multiqc/modules/nanoq/nanoq.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#2743 Bracken: when printing number of found samples, indicate that running Bracken not Kraken
  multiqc/modules/kraken/kraken.py
Labels: module: enhancement

#2737 Improve performance loading large tables in browser
  multiqc/plots/plotly/table.py
  multiqc/templates/default/assets/js/tables.js
Labels: core: front end

#2744 Kraken: refactor, fix top % calculation, more efficient total read count calculation
  multiqc/modules/bracken/bracken.py
  multiqc/modules/kraken/kraken.py
Labels: module: enhancement

#2748 Mosdepth: optimize memory and runtime
  multiqc/base_module.py
  multiqc/modules/mosdepth/mosdepth.py
  multiqc/plots/linegraph.py
Labels: module: enhancement

#2749 Mosdepth: more runtime optimizaiton
  multiqc/modules/mosdepth/mosdepth.py
Labels: module: enhancement

#2751 Split tests of sample versions findings
  tests/test_software_versions.py
Labels: core: infrastructure

#2752 Nonpareil: fix running with >12 samples
  multiqc/modules/nonpareil/nonpareil.py
Labels: bug: module

#2755 Fix adding software versions when `config.run_modules` is set
  multiqc/core/file_search.py
Labels: bug: core

#2757 Anglerfish: adjust for version 0.6.1
  multiqc/modules/anglerfish/anglerfish.py
Labels: module: enhancement

#2756 Kraken: optimize memory and runtime
  multiqc/modules/bracken/bracken.py
  multiqc/modules/kraken/kraken.py
Labels: module: enhancement

#2759 Defer render of plots if number of samples > `config.plots_num_samples_do_not_automatically_load`
  docs/core/getting_started/config.md
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/write_results.py
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/box.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/scatter.py
  multiqc/plots/plotly/violin.py
  multiqc/report.py
  multiqc/templates/default/assets/js/multiqc.js
  multiqc/templates/default/assets/js/plotting.js
  multiqc/templates/default/assets/js/toolbox.js
  multiqc/templates/default/head.html
  multiqc/templates/default/header.html
Labels: core: front end

#2760 Line plot: show markers when num of data points < `config.lineplot_number_of_points_to_hide_markers` (=50)
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/plots/plotly/line.py
Labels: core: front end

#2761 Custom content: allow dict input to heatmap
  multiqc/modules/custom_content/custom_content.py
Labels: custom-content

#2763 FastQC: refactor and type hints
  multiqc/modules/fastqc/fastqc.py
Labels: module: enhancement

#2762 Fix file search performance regression
  multiqc/report.py
Labels: core: back end

#2769 Custom content: cast names to str instead of asserting
  multiqc/modules/custom_content/custom_content.py
Labels: custom-content

#2770 Section order and custom content order: allow skip the `-module` suffix from ID
  multiqc/core/file_search.py
  multiqc/core/order_modules_and_sections.py
  multiqc/modules/custom_content/custom_content.py
  tests/test_custom_content.py
Labels: custom-content

#2771 Cellranger: fix for missing `analysis_tab` data
  multiqc/modules/cellranger/count.py
Labels: bug: module

#2775 Cell Ranger: refactor to get rid of module mixins and fields
  multiqc/modules/cellranger/cellranger.py
  multiqc/modules/cellranger/count.py
  multiqc/modules/cellranger/vdj.py
Labels: module: change

#2778 Peddy sex plot: color predicted sex
  multiqc/modules/peddy/peddy.py
Labels: module: enhancement

#1935 New module: ganon
  .github/workflows/windows.yml
  docs/core/usage/scripts.md
  multiqc/base_module.py
  multiqc/config_defaults.yaml
  multiqc/modules/ganon/__init__.py
  multiqc/modules/ganon/ganon.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#2783 Fix configuring `extra_fn_clean_exts` and `fn_clean_exts` conflict with each other
  multiqc/config.py
Labels: bug: core

#2787 Heatmap: allow numeric `xcats` and `ycats`
  multiqc/plots/heatmap.py
  multiqc/plots/plotly/heatmap.py
  tests/test_custom_content.py
Labels: custom-content

#2788 Freyja: handle empty input, deterministic sample order
  multiqc/modules/freyja/freyja.py
Labels: bug: module, module: enhancement

#2790 FastQC: use interval start instead of average for plots with bp as X axis
  multiqc/modules/fastqc/fastqc.py
Labels: module: enhancement

#2791 FastQC: fix positioning plot status labels when custom anchors set
  multiqc/modules/fastqc/assets/js/multiqc_fastqc.js
Labels: bug: module

#2797 Separate anchors and IDs for sections: use IDs for Python configation, and anchors in HTML
  multiqc/base_module.py
  multiqc/core/order_modules_and_sections.py
  multiqc/core/write_results.py
  multiqc/interactive.py
  multiqc/modules/custom_content/custom_content.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
  multiqc/plots/table_object.py
  multiqc/report.py
  multiqc/templates/default/assets/css/default_multiqc.css
  multiqc/templates/default/assets/js/flat.js
  multiqc/templates/default/assets/js/plots/heatmap.js
  multiqc/templates/default/assets/js/plots/violin.js
  multiqc/templates/default/assets/js/plotting.js
  multiqc/templates/default/assets/js/tables.js
  multiqc/templates/default/assets/js/toolbox.js
  multiqc/templates/default/foot.html
  multiqc/types.py
  tests/test_custom_content.py
  tests/test_plots.py
Labels: custom-content
