Repository MultiQC/MultiQC, pull requests merged in 2024-07, with the labels that each got.

#2670 Re-enable the `software_version` module
  multiqc/core/exec_modules.py
  multiqc/core/file_search.py
  multiqc/core/software_versions.py
  multiqc/interactive.py
  tests/test_interactive.py
  tests/test_software_versions.py
Labels: bug: core

#2674 Custom content parsing fixes and tests
  .github/workflows/mypy.yml
  multiqc/base_module.py
  multiqc/core/exec_modules.py
  multiqc/modules/custom_content/custom_content.py
  multiqc/modules/qc3C/qc3C.py
  multiqc/plots/linegraph.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
  multiqc/report.py
  multiqc/validation.py
  tests/test_custom_content.py
  tests/test_interactive.py
  tests/test_plots.py
  tests/test_run.py
Labels: bug: core

#2683 Line plot series: allow pass lists instead of x/y tuples to work properly with YAML
  multiqc/plots/plotly/line.py
Labels: custom-content

#2649 Custom content: allow hash-fenced table columns
  multiqc/modules/custom_content/custom_content.py
  tests/test_custom_content.py
Labels: custom-content

#2691 Use PR labels and milestones for changelog generation
  scripts/print_changelog.py
Labels: core: infrastructure

#2692 Documentation: update `modules.md`: describe pytest and mypy, plot pydantic classes, PR labels
  docs/core/development/modules.md
Labels: documentation

#2696 Search patterns: allow multiple values for `contents`
  multiqc/report.py
  tests/test_search_files.py
Labels: core: back end

#2690 New module: VG stats
  docs/modules/vg.md
  multiqc/config_defaults.yaml
  multiqc/modules/vg/__init__.py
  multiqc/modules/vg/vg.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#2700 Dockerfile: use `COPY`, copy only relevant files, use Python 3.12
  Dockerfile
Labels: core: infrastructure

#2704 Fix re-loading explicit user configs in interactive sessions
  multiqc/config.py
  multiqc/core/update_config.py
  multiqc/interactive.py
  tests/conftest.py
  tests/test_interactive.py
  tests/test_run.py
Labels: bug: core

#2705 Fix parsing custom content tables with numerical samples
  multiqc/modules/custom_content/custom_content.py
Labels: bug: core, custom-content

#2706 Escape values passed to HTML properties (e.g. `val` in tables)
  multiqc/plots/plotly/table.py
Labels: bug: core

#2698 Umitools: prefer output for sample name, handle <stdin>/<stdout> placeholders
  multiqc/modules/umitools/tests/__init__.py
  multiqc/modules/umitools/tests/test_umitools.py
  multiqc/modules/umitools/umitools.py
Labels: module: enhancement

#2707 Abstract `config.get_cov_thresholds` function for `mosdepth` and `qualimap`; refactor Qualimap
  multiqc/config.py
  multiqc/modules/mosdepth/mosdepth.py
  multiqc/modules/qualimap/QM_BamQC.py
  multiqc/modules/qualimap/QM_RNASeq.py
  multiqc/modules/qualimap/__init__.py
  multiqc/modules/qualimap/qualimap.py
  multiqc/utils/util_functions.py
Labels: module: enhancement

#2231 New module: ngs-bits
  multiqc/config_defaults.yaml
  multiqc/modules/ngsbits/__init__.py
  multiqc/modules/ngsbits/mappingqc.py
  multiqc/modules/ngsbits/ngsbits.py
  multiqc/modules/ngsbits/readqc.py
  multiqc/modules/ngsbits/utils.py
  multiqc/search_patterns.yaml
  multiqc/utils/mqc_colour.py
  pyproject.toml
Labels: module: new

#2708 Search stats: do not double-count
  multiqc/modules/profile_runtime.py
  multiqc/report.py
  multiqc/search_patterns.yaml
Labels: bug: core

#2709 More helpful validation error: print parent class name if applicable
  multiqc/plots/bargraph.py
  multiqc/plots/plotly/line.py
  multiqc/validation.py
  tests/test_custom_content.py
  tests/test_plots.py
Labels: core: back end

#2710 Refactor RSeQC: run `mypy` and remove `multiqc_rseqc.js`
  multiqc/modules/rseqc/assets/js/multiqc_rseqc.js
  multiqc/modules/rseqc/bam_stat.py
  multiqc/modules/rseqc/gene_body_coverage.py
  multiqc/modules/rseqc/infer_experiment.py
  multiqc/modules/rseqc/inner_distance.py
  multiqc/modules/rseqc/junction_annotation.py
  multiqc/modules/rseqc/junction_saturation.py
  multiqc/modules/rseqc/read_distribution.py
  multiqc/modules/rseqc/read_duplication.py
  multiqc/modules/rseqc/read_gc.py
  multiqc/modules/rseqc/rseqc.py
  multiqc/modules/rseqc/tin.py
Labels: core: refactoring

#1148 Pairtools module
  multiqc/config_defaults.yaml
  multiqc/modules/freyja/freyja.py
  multiqc/modules/pairtools/__init__.py
  multiqc/modules/pairtools/pairtools.py
  multiqc/modules/pairtools/params.yml
  multiqc/modules/pairtools/utils.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#2711 Pairtools: fix typos and grammar, remove redundancies
  multiqc/modules/pairtools/pairtools.py
  multiqc/modules/pairtools/utils.py
Labels: module: enhancement

#2714 Spaceranger: refactor and fix ignoring samples
  multiqc/modules/cellranger/utils.py
  multiqc/modules/spaceranger/_utils.py
  multiqc/modules/spaceranger/count.py
  multiqc/modules/spaceranger/spaceranger.py
  multiqc/modules/spaceranger/utils.py
Labels: module: change

#2716 Glimpse: clean and fix filtering samples
  multiqc/modules/glimpse/err_grp.py
  multiqc/modules/glimpse/err_spl.py
  multiqc/modules/glimpse/glimpse.py
Labels: bug: module

#2717 Fix ignoring samples in `spaceranger`, `ngsbits`, `isoseq`, `dragen coverage`
  multiqc/modules/dragen/coverage_per_contig.py
  multiqc/modules/dragen/dragen.py
  multiqc/modules/dragen/overall_mean_cov.py
  multiqc/modules/isoseq/isoseq.py
  multiqc/modules/ngsbits/ngsbits.py
  multiqc/modules/spaceranger/spaceranger.py
Labels: bug: module

#2718 Fix `isoseq` and `odgi` module warnings and error handling
  multiqc/modules/isoseq/isoseq.py
  multiqc/modules/odgi/odgi.py
Labels: core: refactoring

#2713 Move integration test variations into unit tests, actually test them
  .github/workflows/deploy_pypi.yml
  .github/workflows/integration_test.yml
  .github/workflows/integration_tests.yml
  .github/workflows/lint_code.yml
  .github/workflows/mypy.yml
  .github/workflows/unit_tests.yml
  .github/workflows/windows.yml
  multiqc/config.py
  multiqc/core/update_config.py
  multiqc/core/write_results.py
  multiqc/interactive.py
  multiqc/modules/trimmomatic/trimmomatic.py
  multiqc/plots/plotly/plot.py
  multiqc/report.py
  multiqc/templates/default/assets/js/multiqc.js
  multiqc/utils/testing.py
  pyproject.toml
  tests/conftest.py
  tests/test_cmdline.py
  tests/test_custom_content.py
  tests/test_interactive.py
  tests/test_modules_run.py
  tests/test_output_options.py
  tests/test_plots.py
  tests/test_run.py
  tests/test_sample_name_cleaning.py
  tests/test_search_files.py
  tests/test_software_versions.py
Labels: core: infrastructure

#2721 Glimpse: fix parsing data, add proper type hints
  multiqc/modules/glimpse/err_grp.py
  multiqc/modules/glimpse/err_spl.py
Labels: bug: module

#2722 Refactor `write_results` to avoid dynamically overriding `config`, fixes `module.write_data_file`
  multiqc/base_module.py
  multiqc/config.py
  multiqc/core/update_config.py
  multiqc/core/write_results.py
  multiqc/modules/glimpse/err_grp.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/violin.py
  multiqc/report.py
  tests/test_modules_run.py
  tests/test_plots.py
Labels: bug: core, core: refactoring

#2724 Fix toolbox highlight in line plots
  multiqc/templates/default/assets/js/plots/line.js
Labels: bug: core, core: front end

#2725 Actualize the module writing docs
  .github/workflows/docs_preview.yml
  docs/core/development/modules.md
  multiqc/modules/biscuit/biscuit.py
  multiqc/modules/rockhopper/rockhopper.py
Labels: documentation

#1828 STAR: add all alignment summary metrics into a new separate table
  .github/workflows/integration_test.yml
  multiqc/modules/star/star.py
Labels: module: enhancement

#2727 allow multiple custom content to general stats table
  multiqc/modules/custom_content/custom_content.py
Labels: custom-content
