Repository MultiQC/MultiQC, pull requests merged in 2024-01, with the labels that each got.

#2255 Picard: fix using multiple times in report: do not pass `module.anchor` to `self.find_log_files`
  CHANGELOG.md
  multiqc/modules/biobambam2/biobambam2.py
  multiqc/modules/picard/AlignmentSummaryMetrics.py
  multiqc/modules/picard/BaseDistributionByCycleMetrics.py
  multiqc/modules/picard/CrosscheckFingerprints.py
  multiqc/modules/picard/ExtractIlluminaBarcodes.py
  multiqc/modules/picard/GcBiasMetrics.py
  multiqc/modules/picard/HsMetrics.py
  multiqc/modules/picard/IlluminaBasecallingMetrics.py
  multiqc/modules/picard/InsertSizeMetrics.py
  multiqc/modules/picard/MarkDuplicates.py
  multiqc/modules/picard/QualityByCycleMetrics.py
  multiqc/modules/picard/QualityScoreDistributionMetrics.py
  multiqc/modules/picard/QualityYieldMetrics.py
Labels: bug: module, awaits-review

#2257 Mosdepth: Add additional summaries to general stats
  CHANGELOG.md
  docs/modules/mosdepth.md
  multiqc/modules/mosdepth/mosdepth.py
Labels: module: enhancement

#2268 Hifiasm: account for lines with no asterisk
  CHANGELOG.md
  multiqc/modules/hifiasm/hifiasm.py
Labels: bug: module

#2262 New module: MetaPhlAn
  CHANGELOG.md
  docs/modules/metaphlan.md
  multiqc/modules/metaphlan/__init__.py
  multiqc/modules/metaphlan/metaphlan.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new

#2275 Unicode file reading errors: attempt to skip non-unicode characters
  CHANGELOG.md
  multiqc/modules/base_module.py
  multiqc/modules/cutadapt/cutadapt.py
  multiqc/utils/report.py
  multiqc/utils/search_patterns.yaml
Labels: bug: core, awaits-review

#2261 BCLConvert: Add index, project names to sample statistics and calculate mean quality for lane statistics.
  CHANGELOG.md
  multiqc/modules/bclconvert/bclconvert.py
Labels: awaits-review, module: enhancement

#2277 Use alternative method to walk directory using pathlib
  CHANGELOG.md
  multiqc/utils/report.py
Labels: core: back end
