Repository MultiQC/MultiQC, pull requests merged in 2024-02, with the labels that each got.

#2287 Export `config.output_dir` in MegaQC JSON
  CHANGELOG.md
  multiqc/multiqc.py
  multiqc/utils/megaqc.py
Labels: core: back end, awaits-review

#2289 Bcftools: order variant depths plot categories
  CHANGELOG.md
  multiqc/modules/bcftools/stats.py
Labels: bug: module, awaits-review

#2288 BcfTools: add missing `self.ignore_samples` in stats
  CHANGELOG.md
  multiqc/modules/bcftools/stats.py
Labels: bug: module, awaits-review

#1503 Seqwho
  CHANGELOG.md
  docs/modules/seqwho.md
  multiqc/modules/seqwho/__init__.py
  multiqc/modules/seqwho/seqwho.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new, awaits-review

#2281 Cutadapt: support JSON format
  CHANGELOG.md
  docs/modules/cutadapt.md
  multiqc/modules/cutadapt/cutadapt.py
  multiqc/utils/search_patterns.yaml
Labels: awaits-review, module: enhancement

#2265 HUMID: Add cluster statistics
  CHANGELOG.md
  multiqc/modules/homer/tagdirectory.py
  multiqc/modules/humid/clusters.py
  multiqc/modules/humid/counts.py
  multiqc/modules/humid/humid.py
  multiqc/modules/humid/neighbours.py
  multiqc/modules/humid/stats.py
  multiqc/utils/search_patterns.yaml
Labels: awaits-review, module: enhancement

#2227 Add global `shared` flag, remove unnecessary per-module `shared`
  CHANGELOG.md
  docs/core/development/modules.md
  docs/core/usage/troubleshooting.md
  multiqc/utils/config.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/report.py
  multiqc/utils/search_patterns.yaml
Labels: core: back end, awaits-review

#2161 New module: Bamdst
  docs/modules/bamdst.md
  multiqc/modules/bamdst/__init__.py
  multiqc/modules/bamdst/bamdst.py
  multiqc/modules/happy/happy.py
  multiqc/plots/linegraph.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new, awaits-review

#2222 New module: MEGAHIT
  CHANGELOG.md
  docs/modules/megahit.md
  multiqc/modules/megahit/__init__.py
  multiqc/modules/megahit/megahit.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new, awaits-review

#2282 Qualimap: address NBSP as thousand separators
  CHANGELOG.md
  multiqc/modules/qualimap/QM_BamQC.py
  multiqc/modules/qualimap/QM_RNASeq.py
  multiqc/modules/qualimap/__init__.py
Labels: bug: module

#2278 Drop support for module tags
  .github/workflows/multiqc.yml
  CHANGELOG.md
  multiqc/modules/xengsort/xengsort.py
  multiqc/multiqc.py
  multiqc/utils/config.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/util_functions.py
Labels: core: back end

#2291 Multiple datasets in custom content
  CHANGELOG.md
  multiqc/modules/custom_content/custom_content.py
  multiqc/plots/scatter.py
Labels: custom-content, awaits-review

#2292 Make the `default` template use Plotly. Add `highcharts` as a template
  CHANGELOG.md
  multiqc/modules/fastqc/fastqc.py
  multiqc/plots/bargraph.py
  multiqc/plots/beeswarm.py
  multiqc/plots/heatmap.py
  multiqc/plots/linegraph.py
  multiqc/plots/plotly/__init__.py
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/scatter.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
  multiqc/plots/scatter.py
  multiqc/plots/table.py
  multiqc/templates/default/__init__.py
  multiqc/templates/default/assets/css/default_multiqc.css
  multiqc/templates/default/assets/img/MultiQC_logo_dark.svg
  multiqc/templates/default/assets/js/flat.js
  multiqc/templates/default/assets/js/plots/bar.js
  multiqc/templates/default/assets/js/plots/heatmap.js
  multiqc/templates/default/assets/js/plots/line.js
  multiqc/templates/default/assets/js/plots/scatter.js
  multiqc/templates/default/assets/js/plots/violin.js
  multiqc/templates/default/assets/js/plotting.js
  multiqc/templates/default/assets/js/tables.js
  multiqc/templates/default/assets/js/toolbox.js
  multiqc/templates/default/includes.html
  multiqc/templates/highcharts/__init__.py
  multiqc/templates/highcharts/assets/css/default_multiqc.css
  multiqc/templates/highcharts/assets/js/multiqc_mpl.js
  multiqc/templates/highcharts/assets/js/multiqc_plotting.js
  multiqc/templates/highcharts/assets/js/multiqc_tables.js
  multiqc/templates/highcharts/assets/js/multiqc_toolbox.js
  multiqc/templates/highcharts/assets/js/packages/highcharts.export-csv.js
  multiqc/templates/highcharts/assets/js/packages/highcharts.exporting.js
  multiqc/templates/highcharts/assets/js/packages/highcharts.heatmap.js
  multiqc/templates/highcharts/assets/js/packages/highcharts.js
  multiqc/templates/highcharts/assets/js/packages/highcharts.offline-exporting.js
  multiqc/templates/highcharts/includes.html
  multiqc/templates/highcharts/plots/__init__.py
  multiqc/templates/highcharts/plots/bargraph.py
  multiqc/templates/highcharts/plots/beeswarm.py
  multiqc/templates/highcharts/plots/boxplot.py
  multiqc/templates/highcharts/plots/heatmap.py
  multiqc/templates/highcharts/plots/linegraph.py
  multiqc/templates/highcharts/plots/scatter.py
  multiqc/templates/highcharts/plots/table.py
  multiqc/templates/highcharts/plots/table_object.py
  multiqc/templates/plotly/__init__.py
  multiqc/utils/config.py
  multiqc/utils/util_functions.py
  setup.py
Labels: core: back end, awaits-review

#2295 Color ticks in heatmap for highlighted samples [skip changelog]
  multiqc/modules/kraken/kraken.py
  multiqc/plots/linegraph.py
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/heatmap.py
  multiqc/templates/default/assets/js/plots/bar.js
  multiqc/templates/default/assets/js/plots/heatmap.js
  multiqc/templates/default/assets/js/plots/line.js
  multiqc/templates/default/assets/js/plots/scatter.js
  multiqc/templates/default/assets/js/plots/violin.js
  multiqc/templates/default/assets/js/plotting.js
Labels: core: front end

#2299 Fix "Copy Table" behaviour for table+violin
  multiqc/plots/beeswarm.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
  multiqc/plots/table.py
  multiqc/plots/table_object.py
  multiqc/templates/default/assets/js/plots/violin.js
  multiqc/templates/default/assets/js/plotting.js
  multiqc/templates/default/assets/js/tables.js
Labels: core: front end

#2297 BclConvert: handle samples with zero yield
  CHANGELOG.md
  multiqc/modules/bclconvert/bclconvert.py
Labels: bug: module, awaits-review

#2303 CI: re-enable CSP check
  .github/workflows/multiqc.yml
  CSP.txt
Labels: awaits-review, core: infrastructure

#2304 CI: test Windows on a single module to avoid timing out
  .github/workflows/multiqc.yml
  CHANGELOG.md
Labels: core: infrastructure

#2300 Make "Copy Table" button target the `table` element specifically
  multiqc/modules/software_versions.py
  multiqc/plots/plotly/table.py
Labels: core: front end, awaits-review

#2306 Use Plotly `autorangeoptions` instead of `range`. Properly apply floor and ceiling
  CHANGELOG.md
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/plot.py
  multiqc/templates/default/assets/js/plotting.js
Labels: core: front end

#2309 More Plotly cleanup and fixes
  .github/workflows/changelog.py
  CHANGELOG.md
  CSP.txt
  multiqc/modules/rseqc/assets/js/multiqc_rseqc.js
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/violin.py
  multiqc/templates/default/assets/js/plots/violin.js
Labels: core: back end, core: front end

#2313 Minor Plotly cleanup and fixes
  .github/workflows/changelog.py
  CHANGELOG.md
  CSP.txt
  docs/core/development/plots.md
  multiqc/modules/biscuit/biscuit.py
  multiqc/modules/bustools/bustools.py
  multiqc/modules/fastp/fastp.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/rseqc/assets/js/multiqc_rseqc.js
  multiqc/modules/seqera_cli/seqera_cli.py
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/violin.py
  multiqc/templates/default/assets/js/plots/violin.js
Labels: core: back end, core: front end

#2308 Clean up plotting documentation and remove deprecated options [skip changelog]
  CHANGELOG.md
Labels: documentation

#2312 Pin `Pillow` package, wrap add_logo in try-except
  CHANGELOG.md
  multiqc/plots/plotly/plot.py
  setup.py
Labels: awaits-review

#2215 Add nonpareil module
  docs/modules/nonpareil.md
  multiqc/modules/nonpareil/__init__.py
  multiqc/modules/nonpareil/nonpareil.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  setup.py
Labels: module: new

#2314 Configuration: fix reading `config.output_fn_name` and `--filename`
  CHANGELOG.md
  multiqc/multiqc.py
  multiqc/plots/table_object.py
Labels: bug: core, awaits-review

#2321 Group-mode bar plot: fix inner gap
  CHANGELOG.md
  CSP.txt
  multiqc/plots/plotly/bar.py
  multiqc/templates/default/assets/js/plots/bar.js
Labels: core: front end, awaits-review

#2322 Warn if `run_modules` contains a non-existent module
  CHANGELOG.md
  multiqc/multiqc.py
Labels: core: back end, awaits-review

#2325 Pin Plotly and add a runtime version check
  CHANGELOG.md
  multiqc/plots/plotly/__init__.py
  setup.py
Labels: awaits-review

#2330 Always create JSON even when MegaQC upload disabled
  CHANGELOG.md
  multiqc/multiqc.py
Labels: core: back end

#2337 Fix gettng 'id' from optional pconfig=None
  CHANGELOG.md
  multiqc/modules/xengsort/xengsort.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/violin.py
  multiqc/plots/table_object.py
Labels: bug: core, awaits-review

#2340 bcl2fastq: fix the top undetermined barcodes plot
  CHANGELOG.md
  multiqc/modules/bcl2fastq/bcl2fastq.py
Labels: bug: module

#2339 Barplot: keep sample order
  CHANGELOG.md
  CSP.txt
  multiqc/plots/plotly/bar.py
  multiqc/templates/default/assets/js/plots/bar.js
Labels: core: front end

#2341 DRAGEN: add few coverage metrics in general stats
  CHANGELOG.md
  multiqc/modules/dragen/coverage_metrics.py
  multiqc/modules/dragen/ploidy_estimation_metrics.py
Labels: module: change, dragen

#2346 fix general stats for mosdepth
  CHANGELOG.md
  multiqc/modules/mosdepth/mosdepth.py
Labels: bug: module

#2347 DRAGEN: fix showing the number of found samples
  CHANGELOG.md
  multiqc/modules/dragen/coverage_metrics.py
  multiqc/modules/dragen/dragen.py
  multiqc/modules/dragen/ploidy_estimation_metrics.py
  multiqc/modules/dragen/utils.py
Labels: bug: module

#2348 Catch non-hashable values in table data
  CHANGELOG.md
  multiqc/plots/plotly/table.py
Labels: bug: core

#2349 Prevent parsing numerical sample names in heatmap
  CHANGELOG.md
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/heatmap.py
Labels: core: front end

#2351 Changelog bot: do not require PR title start with module name before checking if it is a module change
  .github/workflows/changelog.py
Labels: core: infrastructure

#2350 Interop: do not set `'scale': False` as a default
  CHANGELOG.md
  multiqc/modules/interop/interop.py
Labels: bug: module

#2361 Whatshap: robust to stdout appended to TSV
  multiqc/modules/whatshap/whatshap.py
Labels: module: enhancement

#2359 Drop `full_figure_for_development` the call to avoid Kaleido issues
  CHANGELOG.md
  multiqc/plots/plotly/line.py
Labels: bug: core, core: back end, core: front end

#2366 PURPLE: support v4.0.1 output without `version` column
  CHANGELOG.md
  multiqc/modules/purple/purple.py
Labels: module: change

#2364 Ignore `.parquet` files. More robust `htseq` file reading loop
  CHANGELOG.md
  multiqc/modules/htseq/htseq.py
  multiqc/utils/config_defaults.yaml
Labels: bug: core, bug: module

#2353 Replace `setup.py` with `pyproject.toml`
  .github/RELEASE_CHECKLIST.md
  CHANGELOG.md
  pyproject.toml
  setup.py
Labels: core: infrastructure

#2368 Generic font family for Plotly
  CHANGELOG.md
  multiqc/plots/plotly/plot.py
Labels: awaits-review

#2356 Samtools `coverage` submodule
  CHANGELOG.md
  multiqc/modules/samtools/coverage.py
  multiqc/modules/samtools/flagstat.py
  multiqc/modules/samtools/idxstats.py
  multiqc/modules/samtools/rmdup.py
  multiqc/modules/samtools/samtools.py
  multiqc/modules/samtools/stats.py
  multiqc/plots/plotly/plot.py
  multiqc/utils/search_patterns.yaml
Labels: awaits-review, module: enhancement

#2371 Update `modules.md`: `pyproject.toml`, `"shared_key": "read_count"`, ruffify
  CHANGELOG.md
  docs/core/development/modules.md
Labels: documentation, awaits-review

#2092 Versions API
  README.md
  multiqc/multiqc.py
  multiqc/utils/config.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/util_functions.py
Labels: awaits-review, core: infrastructure

#2374 Box plot adjustment
  CHANGELOG.md
  CSP.txt
  docs/core/development/plots.md
  multiqc/plots/box.py
  multiqc/plots/plotly/box.py
  multiqc/plots/plotly/plot.py
  multiqc/templates/default/assets/js/plots/box.js
Labels: core: front end, WIP

#1591 New module: Iso-Seq
  CHANGELOG.md
  docs/modules/isoseq.md
  multiqc/modules/isoseq/__init__.py
  multiqc/modules/isoseq/isoseq.py
  multiqc/plots/plotly/box.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  pyproject.toml
Labels: module: new, awaits-review

#2378 DRAGEN: Coverage: standardize table
  multiqc/modules/dragen/coverage_metrics.py
Labels: module: enhancement

#2379 Table: replace space with nbsp for user-provided suffixes as well
  multiqc/plots/table_object.py
Labels: core: front end

#2380 Violin plot: filter Inf values
  CHANGELOG.md
  multiqc/plots/plotly/violin.py
Labels: core: back end

#2376 Fix `no_violin`/`no_beeswarm` flag to table
  CHANGELOG.md
  docs/core/development/plots.md
  multiqc/modules/bcl2fastq/bcl2fastq.py
  multiqc/modules/bclconvert/bclconvert.py
  multiqc/modules/clusterflow/clusterflow.py
  multiqc/modules/dragen/coverage_metrics.py
  multiqc/modules/picard/CrosscheckFingerprints.py
  multiqc/modules/somalier/somalier.py
  multiqc/plots/plotly/violin.py
Labels: core: front end

#2381 Fix setting "ylab" from "data_labels"
  multiqc/modules/bcftools/stats.py
  multiqc/modules/samtools/coverage.py
  multiqc/plots/linegraph.py
  multiqc/plots/plotly/plot.py
Labels: core: front end

#2387 Heatmap: add zlab config parameter. Show xlab, ylab, zlab in tooltip
  CHANGELOG.md
  docs/core/development/plots.md
  multiqc/plots/plotly/heatmap.py
Labels: core: front end

#2388 Picard: Crosscheck Fingerprints: add LOD heatmap
  CHANGELOG.md
  multiqc/modules/picard/CrosscheckFingerprints.py
  multiqc/multiqc.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/plot.py
Labels: module: enhancement

#2394 Add export button for table
  CHANGELOG.md
  CSP.txt
  multiqc/modules/nonpareil/nonpareil.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
  multiqc/templates/default/assets/js/plots/violin.js
  multiqc/templates/default/assets/js/tables.js
  multiqc/templates/default/assets/js/toolbox.js
Labels: core: front end

#2397 Add option to place bar plot legend on the bottom
  CHANGELOG.md
  docs/core/reports/customisation.md
  multiqc/plots/plotly/bar.py
  multiqc/utils/config.py
  multiqc/utils/config_defaults.yaml
Labels: core: front end

#2395 Use a padded span with `nowrap` instead of `&nbsp;` before suffixes in table cells
  CHANGELOG.md
  CSP.txt
  multiqc/modules/bamdst/bamdst.py
  multiqc/modules/dragen/utils.py
  multiqc/modules/megahit/megahit.py
  multiqc/modules/preseq/preseq.py
  multiqc/modules/seqera_cli/seqera_cli.py
  multiqc/plots/plotly/table.py
  multiqc/plots/table_object.py
  multiqc/templates/default/assets/css/default_multiqc.css
  multiqc/templates/highcharts/assets/css/default_multiqc.css
  multiqc/templates/highcharts/plots/table.py
Labels: core: front end

#1945 New module: 10x Space Ranger
  .gitignore
  CHANGELOG.md
  docs/modules/spaceranger.md
  multiqc/modules/spaceranger/__init__.py
  multiqc/modules/spaceranger/_utils.py
  multiqc/modules/spaceranger/count.py
  multiqc/modules/spaceranger/spaceranger.py
  multiqc/plots/plotly/table.py
  multiqc/plots/plotly/violin.py
  multiqc/utils/config_defaults.yaml
  multiqc/utils/search_patterns.yaml
  pyproject.toml
Labels: module: new

#2412 Changelog CI: update PR URLs, fix removing existing entry and determining module addition
  .github/workflows/changelog.py
  CHANGELOG.md
Labels: core: infrastructure

#2415 Fix `y_minrange` option
  multiqc/plots/plotly/line.py
Labels: core: front end
