Repository MultiQC/MultiQC, pull requests merged in 2025-07, with the labels that each got.

#3242 Fix custom content description when grouping section with `parent_id`
  multiqc/core/special_case_modules/custom_content.py
  tests/test_custom_content.py
Labels: custom-content

#3244 Add `boxplot_boxpoints` config option to pass to box plot
  docs/markdown/development/plots.md
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/plots/box.py
  multiqc/templates/default/assets/js/plots/box.js
  multiqc/templates/default/head.html
  multiqc/utils/config_schema.py
  tests/test_plots.py
Labels: core: front end

#3246 Custom content: allow passing line plot series as list of tuples in JSON
  multiqc/core/special_case_modules/custom_content.py
  multiqc/plots/linegraph.py
Labels: custom-content

#3257 Always write `llms-full.txt` to multiqc_data
  CHANGELOG.md
  docs/markdown/ai/index.md
  multiqc/core/ai.py
  tests/test_custom_content.py
Labels: ai

#3260 Fix series labels in heatmap subtitle
  multiqc/modules/fastqc/fastqc.py
  multiqc/plots/bargraph.py
  multiqc/plots/box.py
  multiqc/plots/heatmap.py
  multiqc/plots/linegraph.py
  multiqc/plots/plot.py
  multiqc/plots/scatter.py
  multiqc/plots/violin.py
Labels: core: front end

#3261 Somalier: fix sex plot description
  CHANGELOG.md
  multiqc/modules/somalier/somalier.py
Labels: bug: module

#3262 Cutadapt: fix extracting sample name from command line params
  multiqc/modules/cutadapt/cutadapt.py
Labels: bug: module

#3263 UMI-tools: bump up search pattern checked number of lines
  multiqc/search_patterns.yaml
Labels: bug: module

#3267 Fix merging modules from multiple parquet files
  multiqc/core/plot_data_store.py
  multiqc/core/special_case_modules/load_multiqc_data.py
  multiqc/plots/linegraph.py
  multiqc/plots/plot.py
Labels: core: back end

#3280 add before-filtering mean r1/r2 length to general stats
  multiqc/modules/fastp/fastp.py
Labels: module: enhancement
