Repository MultiQC/MultiQC, pull requests merged in 2025-06, with the labels that each got.

#3217 Percolator: handle comments in parsing
  multiqc/modules/percolator/percolator.py
Labels: module: enhancement

#3214 Add samtools ampliconclip stats support
  multiqc/modules/samtools/ampliconclip.py
  multiqc/modules/samtools/samtools.py
  multiqc/search_patterns.yaml
Labels: module: enhancement

#3224 Fix timezone issue
  multiqc/plots/plot.py
Labels: bug: core

#3225 Allow multiline info in module sections
  multiqc/base_module.py
Labels: core: back end, custom-content

#3235 Use `OrderedDict` for `saved_raw_data_keys` to increase performance
  multiqc/base_module.py
  multiqc/plots/table_object.py
  multiqc/report.py
Labels: core: back end

#3241 Use universal `config.use_filename_as_sample_name`, depreate module-specific flags
  docs/markdown/getting_started/config.md
  multiqc/base_module.py
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/update_config.py
  multiqc/modules/fastp/fastp.py
  multiqc/modules/picard/util.py
  multiqc/modules/prokka/prokka.py
  multiqc/modules/trimmomatic/trimmomatic.py
  multiqc/modules/verifybamid/verifybamid.py
  multiqc/utils/config_schema.json
  multiqc/utils/config_schema.py
  tests/test_modules_run.py
Labels: core: back end
