Repository MultiQC/MultiQC, pull requests merged in 2025-04, with the labels that each got.

#3148 Fix barplot CSV in-browser export
  multiqc/templates/default/assets/js/plots/bar.js
Labels: bug: core, core: front end

#3149 Handle timezone locale error
  multiqc/report.py
Labels: bug: core

#3154 Add docs mentioning JSON schema store
  docs/markdown/getting_started/config.md
Labels: documentation

#3123 New module: Elembio bases2fastq
  multiqc/modules/bases2fastq/__init__.py
  multiqc/modules/bases2fastq/bases2fastq.py
  multiqc/modules/bases2fastq/plot_project_runs.py
  multiqc/modules/bases2fastq/plot_runs.py
  multiqc/modules/bases2fastq/plot_samples.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#3118 Use parquet as intermediate format
  .github/workflows/integration_test.yml
  .github/workflows/mypy.yml
  .github/workflows/unit_tests.yml
  multiqc/base_module.py
  multiqc/core/ai.py
  multiqc/core/exec_modules.py
  multiqc/core/file_search.py
  multiqc/core/plot_data_store.py
  multiqc/core/special_case_modules/custom_content.py
  multiqc/core/special_case_modules/load_multiqc_data.py
  multiqc/core/special_case_modules/profile_runtime.py
  multiqc/core/tmp_dir.py
  multiqc/core/write_results.py
  multiqc/interactive.py
  multiqc/modules/clipandmerge/clipandmerge.py
  multiqc/modules/fastp/fastp.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/flexbar/flexbar.py
  multiqc/modules/htseq/htseq.py
  multiqc/modules/humid/stats.py
  multiqc/modules/macs2/macs2.py
  multiqc/modules/picard/RnaSeqMetrics.py
  multiqc/modules/picard/TargetedPcrMetrics.py
  multiqc/modules/picard/VariantCallingMetrics.py
  multiqc/modules/qc3C/qc3C.py
  multiqc/modules/qorts/qorts.py
  multiqc/modules/rsem/rsem.py
  multiqc/modules/samtools/flagstat.py
  multiqc/modules/seqera_cli/seqera_cli.py
  multiqc/modules/slamdunk/slamdunk.py
  multiqc/modules/somalier/somalier.py
  multiqc/modules/umicollapse/tests/test_umicollapse.py
  multiqc/modules/umitools/tests/test_umitools.py
  multiqc/modules/varscan2/varscan2.py
  multiqc/plots/bargraph.py
  multiqc/plots/box.py
  multiqc/plots/heatmap.py
  multiqc/plots/linegraph.py
  multiqc/plots/plot.py
  multiqc/plots/scatter.py
  multiqc/plots/table.py
  multiqc/plots/table_object.py
  multiqc/plots/violin.py
  multiqc/report.py
  multiqc/search_patterns.yaml
  multiqc/templates/default/nav.html
  multiqc/types.py
  multiqc/utils/util_functions.py
  pyproject.toml
  tests/test_custom_content.py
  tests/test_modules_run.py
  tests/test_natsort_files.py
  tests/test_plots.py
  tests/test_rerun.py
Labels: core: back end

#3137 sort custom-content by section name by default
  multiqc/core/special_case_modules/custom_content.py
Labels: custom-content

#3158 Bases2Fastq: update links and definitions
  multiqc/modules/bases2fastq/bases2fastq.py
  multiqc/modules/bases2fastq/plot_project_runs.py
  multiqc/modules/bases2fastq/plot_runs.py
  multiqc/modules/bases2fastq/plot_samples.py
Labels: module: change

#3159 Do not crash if failed to remove tmp dir
  multiqc/core/tmp_dir.py
  multiqc/core/write_results.py
  multiqc/report.py
Labels: core: back end

#3160 Customize plot subtitle ("N samples")
  multiqc/modules/fastqc/fastqc.py
  multiqc/plots/plot.py
Labels: core: front end

#3157 Use killable processes for kaleido plot export
  multiqc/core/log_and_rich.py
  multiqc/core/write_results.py
  multiqc/plots/plot.py
  tests/test_plots.py
Labels: core: back end, kaleido

#3163 NanoStat: allow customizing general stats columns
  docs/markdown/reports/customisation.md
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/modules/nanostat/nanostat.py
  multiqc/utils/config_schema.py
Labels: core: back end, module: enhancement

#3165 Minor installation docs tweaks:
  .github/RELEASE_CHECKLIST.md
  docs/markdown/getting_started/installation.md
  docs/markdown/getting_started/quick_start.md
  docs/markdown/modules/interop.md
  multiqc/modules/interop/interop.py
Labels: documentation

#3164 Generalize customizing general stats columns, support samtools
  docs/markdown/reports/customisation.md
  multiqc/base_module.py
  multiqc/config.py
  multiqc/modules/nanostat/nanostat.py
  multiqc/modules/samtools/coverage.py
  multiqc/modules/samtools/flagstat.py
  multiqc/modules/samtools/markdup.py
  multiqc/modules/samtools/rmdup.py
  multiqc/modules/samtools/samtools.py
  multiqc/modules/samtools/stats.py
  multiqc/utils/__init__.py
Labels: core: back end, module: enhancement

#3169 Document `multiqc.parse_logs("multiqc.parquet")`
  docs/markdown/usage/scripts.md
  multiqc/interactive.py
  multiqc/plots/violin.py
  tests/test_interactive.py
Labels: bug: core

#3170 Fix notebook example docs link
  docs/markdown/usage/scripts.md
Labels: documentation

#3171 Optimize parquet format
  multiqc/core/plot_data_store.py
  multiqc/core/special_case_modules/load_multiqc_data.py
  multiqc/interactive.py
  multiqc/modules/fastp/fastp.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/plots/bargraph.py
  multiqc/plots/box.py
  multiqc/plots/heatmap.py
  multiqc/plots/linegraph.py
  multiqc/plots/plot.py
  multiqc/plots/scatter.py
  multiqc/plots/table_object.py
  multiqc/plots/violin.py
  multiqc/utils/config_schema.py
  tests/test_rerun.py
Labels: core: back end

#3173 Make sure multiqc.log has full debug log
  multiqc/core/log_and_rich.py
  multiqc/core/plot_data_store.py
  multiqc/core/write_results.py
Labels: core: back end
