Repository MultiQC/MultiQC, pull requests merged in 2025-08, with the labels that each got.

#3289 Missing modules to general stats: Busco, CheckM, CheckM2, GTDB-Tk
  multiqc/modules/busco/busco.py
  multiqc/modules/checkm/checkm.py
  multiqc/modules/checkm2/checkm2.py
  multiqc/modules/gtdbtk/gtdbtk.py
Labels: module: enhancement

#3295 bcftools: fix singleton count calculation to include indels
  multiqc/modules/bcftools/stats.py
Labels: bug: module

#3296 Replace deprecated hide_empty with hide_zero_cats
  multiqc/modules/afterqc/afterqc.py
  multiqc/modules/bamdst/bamdst.py
  multiqc/modules/bcl2fastq/bcl2fastq.py
  multiqc/modules/bclconvert/bclconvert.py
  multiqc/modules/biobloomtools/biobloomtools.py
  multiqc/modules/dragen_fastqc/content_metrics.py
  multiqc/modules/fastq_screen/fastq_screen.py
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/humid/clusters.py
  multiqc/modules/humid/counts.py
  multiqc/modules/humid/neighbours.py
  multiqc/modules/mosdepth/mosdepth.py
  multiqc/modules/multivcfanalyzer/multivcfanalyzer.py
  multiqc/modules/qc3C/qc3C.py
  multiqc/modules/samtools/coverage.py
  multiqc/modules/sequali/sequali.py
  multiqc/plots/linegraph.py
Labels: bug: module

#3276 New module: Xenium QC
  .github/workflows/windows.yml
  multiqc/config_defaults.yaml
  multiqc/modules/xenium/__init__.py
  multiqc/modules/xenium/xenium.py
  multiqc/plots/bargraph.py
  multiqc/plots/box.py
  multiqc/plots/scatter.py
  multiqc/plots/violin.py
  multiqc/report.py
  multiqc/search_patterns.yaml
  multiqc/templates/default/assets/js/plots/bar.js
  multiqc/templates/default/assets/js/plots/box.js
  multiqc/templates/default/assets/js/plots/scatter.js
  pyproject.toml
Labels: module: new

#3302 Fix fastp sample naming for paired-end reads
  multiqc/modules/fastp/fastp.py
Labels: bug: module

#3298 Picard: fix VariantCallingMetrics to support sample renaming
  multiqc/modules/picard/VariantCallingMetrics.py
Labels: bug: module

#3307 Picard: enhance QualityByCycleMetrics to support original quality scores
  multiqc/modules/picard/QualityByCycleMetrics.py
Labels: module: enhancement

#3312 File search: do not read files if contents exclusion patterns are not provided
  .gitignore
  multiqc/modules/umicollapse/tests/test_umicollapse.py
  multiqc/modules/umitools/tests/test_umitools.py
  multiqc/report.py
  tests/test_custom_content.py
  tests/test_modules_run.py
  tests/test_plots.py
  tests/test_sample_name_cleaning.py
  tests/test_search_files.py
Labels: core: back end

#3321 Scatter plot: fix hiding dots by legend click
  multiqc/templates/default/assets/js/plots/scatter.js
Labels: core: front end
