Repository MultiQC/MultiQC, pull requests merged in 2025-09, with the labels that each got.

#3320 Ignore pyc files when copying html files
  multiqc/core/write_results.py
Labels: bug: core

#3329 docs: Fix links causing Docusaurus warnings
  docs/markdown/getting_started/installation.md
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/featurecounts/featurecounts.py
Labels: documentation

#3330 Unique series label for each plot type
  multiqc/modules/fastqc/fastqc.py
  multiqc/modules/xenium/xenium.py
  multiqc/plots/plot.py
Labels: core: front end

#3334 Xenium: fix `Transcript Quality Summary ` order. Add warnings about missing `scipy`
  multiqc/modules/xenium/xenium.py
  pyproject.toml
Labels: module: enhancement

#3186 New module: sompy
  .github/workflows/docker.yml
  multiqc/modules/happy/happy.py
  multiqc/modules/sompy/__init__.py
  multiqc/modules/sompy/sompy.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new
