Repository MultiQC/MultiQC, pull requests merged in 2025-05, with the labels that each got.

#3174 Add option `--only-samples` - opposit of `--ignore-samples`
  multiqc/base_module.py
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/update_config.py
  multiqc/multiqc.py
  multiqc/utils/config_schema.py
Labels: core: back end

#3175 Use timestamp type in parquet files suitable for Iceberg
  multiqc/config_defaults.yaml
  multiqc/core/plot_data_store.py
  multiqc/core/special_case_modules/load_multiqc_data.py
Labels: core: back end

#3176 New module: cells2stats. Support run statistics JSON output
  multiqc/modules/bases2fastq/bases2fastq.py
  multiqc/modules/cells2stats/__init__.py
  multiqc/modules/cells2stats/cells2stats.py
  multiqc/modules/cells2stats/cells2stats_bar_plots.py
  multiqc/modules/cells2stats/cells2stats_tables.py
  multiqc/modules/cells2stats/queries.py
  multiqc/modules/cells2stats/utils.py
  multiqc/search_patterns.yaml
  pyproject.toml
Labels: module: new

#3122 Headers for AzureAI: add `config.ai_auth_type`
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/ai.py
  multiqc/utils/config_schema.py
Labels: ai

#3181 Fix applying `data_labels` extra parameters in plot config
  multiqc/modules/cells2stats/cells2stats_bar_plots.py
  multiqc/plots/bargraph.py
  multiqc/plots/box.py
  multiqc/plots/heatmap.py
  multiqc/plots/linegraph.py
  multiqc/plots/plot.py
  multiqc/plots/scatter.py
  multiqc/utils/config_schema.py
Labels: core: front end

#3184 Custom content: fix when section id and plot anchor are identical
  multiqc/core/special_case_modules/custom_content.py
Labels: custom-content

#3115 AWS Bedrock support for AI summaries (#3115)
  docs/markdown/ai/index.md
  multiqc/core/ai.py
  multiqc/core/update_config.py
  multiqc/templates/default/assets/js/toolbox.js
  multiqc/utils/config_schema.json
  multiqc/utils/config_schema.py
  pyproject.toml
Labels: ai

#3189 Bases2Fastq: support handling of single-end sequencing data
  multiqc/modules/bases2fastq/bases2fastq.py
  multiqc/modules/bases2fastq/plot_runs.py
  multiqc/modules/bases2fastq/plot_samples.py
Labels: module: enhancement

#3193 Fix false auto-opening toolbox when SeqeraAI is selected
  multiqc/templates/default/assets/js/ai.js
Labels: ai

#3196 bcftools stats - enable log switch for indel plot
  multiqc/modules/bcftools/stats.py
  tests/test_plots.py
Labels: module: enhancement

#3194 Parquet: format improvements. Allow to select wide or long format.
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/ai.py
  multiqc/core/plot_data_store.py
  multiqc/core/special_case_modules/load_multiqc_data.py
  multiqc/plots/bargraph.py
  multiqc/plots/box.py
  multiqc/plots/heatmap.py
  multiqc/plots/linegraph.py
  multiqc/plots/plot.py
  multiqc/plots/scatter.py
  multiqc/plots/violin.py
  multiqc/utils/config_schema.py
  pyproject.toml
  tests/test_rerun.py
Labels: core: back end

#3198 PRINSEQ++: Fix logger warnings
  multiqc/modules/prinseqplusplus/prinseqplusplus.py
Labels: module: enhancement

#3204 Custom Content: Support Markdown
  CHANGELOG.md
  multiqc/core/special_case_modules/custom_content.py
  multiqc/search_patterns.yaml
  tests/test_custom_content.py
Labels: custom-content

#3212 Picard: new OxoGMetrics search pattern
  multiqc/search_patterns.yaml
Labels: module: enhancement
