Repository MultiQC/MultiQC, pull requests merged in 2025-02, with the labels that each got.

#3074 Anonymize sample names
  docs/markdown/ai/index.md
  multiqc/base_module.py
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/ai.py
  multiqc/modules/peddy/peddy.py
  multiqc/plots/box.py
  multiqc/plots/linegraph.py
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/box.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/scatter.py
  multiqc/plots/plotly/violin.py
  multiqc/plots/scatter.py
  multiqc/report.py
  multiqc/templates/default/assets/js/ai-helpers.js
  multiqc/templates/default/assets/js/plots/bar.js
  multiqc/templates/default/assets/js/plots/box.js
  multiqc/templates/default/assets/js/plots/heatmap.js
  multiqc/templates/default/assets/js/plots/line.js
  multiqc/templates/default/assets/js/plots/scatter.js
  multiqc/templates/default/assets/js/plots/violin.js
  multiqc/templates/default/assets/js/plotting.js
  multiqc/templates/default/assets/js/toolbox.js
  multiqc/templates/default/head.html
  multiqc/templates/default/toolbox.html
Labels: planned, ai

#3081 Table scatter plot: remove legend to make more space
  multiqc/templates/default/assets/js/tables.js
Labels: core: front end

#3082 Table scatters: support hide, rename, highlight
  multiqc/templates/default/assets/js/tables.js
Labels: core: front end

#3083 Add option to provider custom OpenAI endpoint
  docs/markdown/ai/index.md
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/ai.py
  multiqc/core/update_config.py
  multiqc/multiqc.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/plotly/table.py
  multiqc/report.py
  multiqc/templates/default/assets/css/default_multiqc.css
  multiqc/templates/default/assets/js/ai-helpers.js
  multiqc/templates/default/assets/js/ai.js
  multiqc/templates/default/assets/js/plots/line.js
  multiqc/templates/default/assets/js/plots/scatter.js
  multiqc/templates/default/assets/js/plotting.js
  multiqc/templates/default/assets/js/toolbox.js
  multiqc/templates/default/head.html
  multiqc/templates/default/header.html
  multiqc/templates/default/toolbox.html
Labels: ai

#3086 Handle empty custom content files
  multiqc/modules/custom_content/custom_content.py
  tests/test_custom_content.py
Labels: custom-content

#3094 Fix warnings when "read_count_multiplier: 1"
  multiqc/plots/table_object.py
Labels: bug: core

#3095 Fix generating AI summaries from custom content table with empty cells
  .pre-commit-config.yaml
  multiqc/plots/plotly/violin.py
Labels: ai

#3096 AI in-browser summary: fix prompt for string-type cells in tables
  multiqc/templates/default/assets/js/plots/violin.js
Labels: bug: core, ai

#3091 QUAST: add ANI column
  multiqc/modules/quast/quast.py
Labels: module: enhancement

#3097 Ignore `*.jar` files for file search
  multiqc/config_defaults.yaml
Labels: core: back end

#3098 Trimmomatic: use more specific sesarch pattern
  multiqc/search_patterns.yaml
Labels: module: enhancement

#3101 BCLConvert - Fix index parsing
  multiqc/modules/bclconvert/bclconvert.py
Labels: bug: module
