Repository MultiQC/MultiQC, pull requests merged in 2025-01, with the labels that each got.

#3038 Preseq: fix parsing `nan` and add strict type hints
  multiqc/modules/preseq/preseq.py
  multiqc/plots/plotly/line.py
Labels: bug: module

#3044 Preserve order of `saved_raw_data_keys`
  multiqc/base_module.py
  multiqc/plots/plotly/table.py
  multiqc/report.py
Labels: core: back end

#3045 Make tables Configure Column max columns configurable
  docs/markdown/development/plots.md
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/plots/plotly/table.py
Labels: bug: core, core: front end

#3046 Checkm2: handle v1.0.1, be less strict to header columns
  multiqc/modules/checkm/checkm.py
  multiqc/modules/checkm2/checkm2.py
  multiqc/search_patterns.yaml
Labels: module: enhancement

#3048 Update ruff and pre-commit
  .github/workflows/lint_code.yml
  .github/workflows/seqera_docs_changelog.py
  .pre-commit-config.yaml
  multiqc/core/software_versions.py
  multiqc/modules/bbmap/bbmap_filetypes.py
  multiqc/modules/clusterflow/clusterflow.py
  multiqc/modules/dragen/vc_metrics.py
  multiqc/modules/fastp/fastp.py
  multiqc/modules/goleft_indexcov/goleft_indexcov.py
  multiqc/modules/kraken/kraken.py
  multiqc/modules/mosdepth/mosdepth.py
  multiqc/modules/nanostat/nanostat.py
  multiqc/modules/ngsbits/mappingqc.py
  multiqc/modules/ngsbits/readqc.py
  multiqc/modules/picard/AlignmentSummaryMetrics.py
  multiqc/modules/picard/IlluminaLaneMetrics.py
  multiqc/modules/picard/MarkDuplicates.py
  multiqc/modules/picard/OxoGMetrics.py
  multiqc/modules/picard/ValidateSamFile.py
  multiqc/modules/porechop/porechop.py
  multiqc/modules/samtools/stats.py
  multiqc/modules/sequali/sequali.py
  multiqc/modules/software_versions.py
  multiqc/modules/xenome/xenome.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/plot.py
  multiqc/plots/scatter.py
  multiqc/report.py
  multiqc/validation.py
Labels: core: infrastructure

#3041 Add "Continue with Seqera AI" button
  multiqc/core/ai.py
  multiqc/report.py
  multiqc/templates/default/assets/css/default_multiqc.css
  multiqc/templates/default/assets/js/ai-helpers.js
  multiqc/templates/default/assets/js/ai.js
  multiqc/templates/default/content.html
  multiqc/templates/default/general_stats.html
  multiqc/templates/default/header.html
Labels: awaits-review

#3053 Support bustools 0.44.1
  multiqc/modules/bustools/bustools.py
Labels: module: enhancement

#3056 Update module docs
  docs/markdown/modules.mdx
  docs/markdown/modules/cellranger_arc.md
  docs/markdown/modules/checkm.md
  docs/markdown/modules/checkm2.md
  docs/markdown/modules/gtdbtk.md
  docs/markdown/modules/haplocheck.md
  docs/markdown/modules/mgikit.md
  docs/markdown/modules/percolator.md
Labels: documentation

#3058 Custom content: Support `.gif`, `.webp` and `.tiff`
  docs/markdown/custom_content/index.md
  multiqc/modules/custom_content/custom_content.py
  multiqc/report.py
  multiqc/search_patterns.yaml
Labels: custom-content

#3059 Parsing custom content TSV: allow leading empty columns
  multiqc/modules/custom_content/custom_content.py
Labels: custom-content

#3063 Do not print stack trace on KeyboardInterrupt unless verbose
  multiqc/multiqc.py
Labels: core: back end

#3064 Use `tiktoken` to estimate token counts for all providers
  multiqc/core/ai.py
  pyproject.toml
Labels: ai

#3066 Remove `langchain` dependency
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/ai.py
  pyproject.toml
Labels: ai

#3071 Make token count warning a debug
  multiqc/core/ai.py
Labels: ai

#3072 Config from env: resolve empty to Null
  multiqc/config.py
Labels: core: back end

#3075 FastQC: fix "Per Base Sequence Content" heatmap
  multiqc/templates/default/content.html
Labels: bug: core

#3077 Box plot AI repro: use statistics instead of raw values, support static version
  multiqc/plots/plotly/box.py
  multiqc/templates/default/assets/js/plots/box.js
Labels: ai
