Repository MultiQC/MultiQC, pull requests merged in 2025-03, with the labels that each got.

#3109 AI prompt optimizations
  multiqc/config.py
  multiqc/core/ai.py
  multiqc/plots/plotly/bar.py
  multiqc/plots/plotly/box.py
  multiqc/plots/plotly/heatmap.py
  multiqc/plots/plotly/line.py
  multiqc/plots/plotly/scatter.py
  multiqc/plots/plotly/violin.py
  multiqc/templates/default/assets/js/plots/bar.js
  multiqc/templates/default/assets/js/plots/box.js
  multiqc/templates/default/assets/js/plots/heatmap.js
  multiqc/templates/default/assets/js/plots/line.js
  multiqc/templates/default/assets/js/plots/violin.js
Labels: ai

#3112 Bargraph: respect `pconfig.use_legend` if defined
  multiqc/plots/plotly/bar.py
Labels: core: front end

#3114 Move special case modules into core
  .cursorignore
  multiqc/core/ai.py
  multiqc/core/order_modules_and_sections.py
  multiqc/core/special_case_modules/custom_content.py
  multiqc/core/special_case_modules/profile_runtime.py
  multiqc/core/special_case_modules/software_versions.py
  multiqc/modules/custom_content/__init__.py
  pyproject.toml
  tests/test_custom_content.py
  tests/test_modules_run.py
  tests/test_software_versions.py
Labels: core: refactoring

#3116 Small VEP fix when data in category is missing
  multiqc/modules/vep/vep.py
Labels: bug: module

#3124 Round table values for AI prompt
  multiqc/core/ai.py
  multiqc/plots/table_object.py
  multiqc/plots/violin.py
  tests/test_custom_content.py
Labels: ai

#3135 Fix setting `custom_table_header_config` for custom table
  multiqc/plots/table_object.py
Labels: bug: core, custom-content

#3129 ignore formatting errors when generating ai summary from violin plot
  multiqc/plots/violin.py
Labels: ai

#3131 allow customizing prompt sent to llm
  multiqc/config.py
  multiqc/config_defaults.yaml
  multiqc/core/ai.py
  multiqc/core/update_config.py
  multiqc/utils/config_schema.py
Labels: ai

#3128 fix npe when generating ai table from violin plot
  multiqc/plots/violin.py
Labels: ai

#3140 Tix pre-configured table sort `defaultsort`
  multiqc/plots/table.py
  tests/test_plots.py
Labels: core: front end

#3143 kraken: hide read-count decimals for taxa plot
  multiqc/modules/kraken/kraken.py
Labels: bug: module
